// Generated by CodiumAI

import { render } from '@testing-library/react';

import { DateInput } from './DateInput';

describe('DateInput', () => {
  // Renders input with initial selected date
  it('should render input with initial selected date', () => {
    const { getByPlaceholderText } = render(
      <DateInput selectedDate={new Date('2023-10-01')} onSelect={() => {}} />
    );
    const input = getByPlaceholderText('Please select a date');
    expect(input).toHaveValue('10/1/2023');
  });

  // Handles empty input value gracefully
  it('should handle empty input value gracefully', () => {
    const { getByPlaceholderText } = render(
      <DateInput selectedDate={undefined} onSelect={() => {}} />
    );
    const input = getByPlaceholderText('Please select a date');
    expect(input).toHaveValue('');
  });
});
