// Generated by CodiumAI

import {
  formatUSDollars,
  formatUSDollarsAccounting,
  parseNumber,
} from './currency';
import { DEFAULT_ERROR_STRING } from './strings';

describe('parseNumber', () => {
  // Returns DEFAULT_ERROR_STRING when given a null value.
  it('should return null when given a null value', () => {
    const result = parseNumber(null);
    expect(result).toEqual(DEFAULT_ERROR_STRING);
  });

  // Returns DEFAULT_ERROR_STRING when given an undefined value.
  it('should return null when given an undefined value', () => {
    const result = parseNumber(undefined);
    expect(result).toEqual(DEFAULT_ERROR_STRING);
  });

  // Returns DEFAULT_ERROR_STRING when given a non-number value.
  it('should return null when given a non-number value', () => {
    const result = parseNumber('abc');
    expect(result).toEqual(DEFAULT_ERROR_STRING);
  });

  // Returns number when given a number as string.
  it('should return null when given a non-number value', () => {
    const result = parseNumber('564');
    expect(result).toEqual(564);
  });

  // Returns $0 when given an undefined value and displayNullAsZero is true
  it('should return formatted 0 when given an undefined value and displayNullAsZero is true', () => {
    const result = parseNumber(undefined, true);
    expect(result).toEqual('$0');
  });
});

describe('formatUSDollars', () => {
  // Returns a formatted USD currency string when given a valid number.
  it('should return a formatted USD currency string when given a valid number', () => {
    const result = formatUSDollars(1000);
    expect(result).toEqual('$1,000.00');
  });

  // Returns $0 when given an undefined value and displayNullAsZero is true
  it('should return null when given an undefined value', () => {
    const result = formatUSDollars(undefined, true);
    expect(result).toEqual('$0');
  });

  // Returns a formatted USD currency string when given a negative number.
  it('should return a formatted USD currency string when given a negative number', () => {
    const result = formatUSDollars(-1000);
    expect(result).toEqual('-$1,000.00');
  });

  // Returns a formatted USD currency string when given a zero value.
  it('should return a formatted USD currency string when given a zero value', () => {
    const result = formatUSDollars(0);
    expect(result).toEqual('$0');
  });

  // Returns a formatted USD currency with letter if value is 1 million or more.
  it('should return a formatted USD currency string when given a zero value', () => {
    const result = formatUSDollars(1000000, false, true);
    expect(result).toEqual('$1M');
  });
});

describe('formatUSDollarsAccounting', () => {
  // Formats positive numbers correctly in USD
  it('should format positive numbers correctly in USD when given a valid number', () => {
    const result = formatUSDollarsAccounting(1234.56);
    expect(result).toBe('$1,234.56');
  });

  // Handles negative numbers
  it('should return parenthetical negative display when passed a negative number', () => {
    const result = formatUSDollarsAccounting(-400);
    expect(result).toBe('($400.00)');
  });

  // Handles non-numeric strings gracefully
  it('should return the input when given a non-numeric string', () => {
    const result = formatUSDollarsAccounting('abc');
    expect(result).toBe(DEFAULT_ERROR_STRING);
  });
});
