// Generated by CodiumAI
import { formatUSDollars } from './currency';

describe('formatUSDollars', () => {
  // Returns a formatted USD currency string when given a valid number.
  it('should return a formatted USD currency string when given a valid number', () => {
    const result = formatUSDollars(1000);
    expect(result).toEqual('$1,000.00');
  });

  // Returns null when given a null value.
  it('should return null when given a null value', () => {
    const result = formatUSDollars(null);
    expect(result).toBeNull();
  });

  // Returns null when given an undefined value.
  it('should return null when given an undefined value', () => {
    const result = formatUSDollars(undefined);
    expect(result).toBeNull();
  });

  // Returns null when given a non-number value.
  it('should return null when given a non-number value', () => {
    const result = formatUSDollars('abc');
    expect(result).toBeNull();
  });

  // Returns a formatted USD currency string when given a negative number.
  it('should return a formatted USD currency string when given a negative number', () => {
    const result = formatUSDollars(-1000);
    expect(result).toEqual('-$1,000.00');
  });

  // Returns a formatted USD currency string when given a zero value.
  it('should return a formatted USD currency string when given a zero value', () => {
    const result = formatUSDollars(0);
    expect(result).toEqual('$0.00');
  });
});
