// Generated by CodiumAI

import {
  Phone,
  PhoneType,
  PolicyStatus,
  Policy,
} from '@zinnia/api-types/types/sor';
import dayjs from 'dayjs';

import {
  ItemsWithEndDate,
  allowedAnnualWithdrawals,
  bankAccountNumberSanitizer,
  checkIfNull,
  filterItemsWithPastEndDate,
  formatPhoneNumberWithExtension,
  fullName,
  isEndDatedAndEndDateUpcoming,
} from './data';
import { DEFAULT_ERROR_STRING } from './strings';
import { BestTimeType } from '../components/person-data/types';

describe('isEndDatedAndEndDateUpcoming', () => {
  // Returns true if endDate is in the past
  it('should return true when endDate is in the past', () => {
    const endDate = '2021-01-01';
    const result = isEndDatedAndEndDateUpcoming(endDate);
    expect(result).toBe(true);
  });

  // Returns false if endDate is an empty string
  it('should return false when endDate is an empty string', () => {
    const endDate = '';
    const result = isEndDatedAndEndDateUpcoming(endDate);
    expect(result).toBe(false);
  });
});

describe('filterItemsWithPastEndDate', () => {
  // Returns an empty array when given an empty array as input.
  it('should return an empty array when given an empty array as input', () => {
    const items: ItemsWithEndDate[] = [];
    const result = filterItemsWithPastEndDate(items);
    expect(result).toEqual([]);
  });

  // Returns an empty array when given null as input.
  it('should return an empty array when given null as input', () => {
    const items = undefined;
    const result = filterItemsWithPastEndDate(items);
    expect(result).toEqual([]);
  });
});

// Generated by CodiumAI

describe('formatPhoneNumberWithExtension', () => {
  // Should format a phone number with all fields provided
  it('should format a phone number with all fields provided', () => {
    const phone: Phone = {
      phoneId: '1',
      startDate: '2022-01-01',
      endDate: '2022-12-31',
      phoneType: PhoneType.HOME,
      countryCode: '1',
      areaCode: '123',
      dialNumber: '4567890',
      extension: '1234',
      bestTime: BestTimeType.Afternoon,
    };

    const formattedNumber = formatPhoneNumberWithExtension(phone);

    expect(formattedNumber).toBe('+1 (123) 456-7890 ext. 1234');
  });

  // Should format a phone number with a countryCode of length 1
  it('should format a phone number with a countryCode of length 1', () => {
    const phone: Phone = {
      phoneId: '2',
      startDate: '2022-01-01',
      endDate: '2022-12-31',
      phoneType: PhoneType.MOBILE,
      countryCode: '9',
      areaCode: '987',
      dialNumber: '6543210',
      extension: '',
      bestTime: BestTimeType.Morning,
    };

    const formattedNumber = formatPhoneNumberWithExtension(phone);

    expect(formattedNumber).toBe('+9 (987) 654-3210');
  });
});

// Generated by CodiumAI

describe('fullName', () => {
  // Returns the full name when both first name and last name are provided
  it('should return the full name when both first name and last name are provided', () => {
    const result = fullName({ firstName: 'John', lastName: 'Doe' });
    expect(result).toBe('John Doe');
  });

  // Returns the full name with proper capitalization when first name and last name are in different cases
  it('should return the full name with proper capitalization when first name and last name are in different cases', () => {
    const result = fullName({ firstName: 'jOhN', lastName: 'dOe' });
    expect(result).toBe('John Doe');
  });

  // Returns only the last name when first name is not provided
  it('should return default error string with last name when first name is not provided', () => {
    const result = fullName({ firstName: '', lastName: 'Doe' });
    expect(result).toBe('- Doe');
  });

  // Returns the default error string when both first name and last name are not provided
  it('should return the default error string when both first name and last name are not provided', () => {
    const result = fullName({ firstName: '', lastName: '' });
    expect(result).toBe(DEFAULT_ERROR_STRING);
  });
});

// Generated by CodiumAI

describe('checkIfNull', () => {
  // Returns the value if it is not null and zeroIsValid is true
  it('should return the value when it is not null and zeroIsValid is true', () => {
    const value = 10;
    const result = checkIfNull(value, true);
    expect(result).toBe(value);
  });

  // Returns '-' if value is null
  it('should return "-" when the value is null', () => {
    const value = null;
    const result = checkIfNull(value);
    expect(result).toBe(DEFAULT_ERROR_STRING);
  });

  // Returns '-' if value is null and zeroIsValid is false
  it('should return "-" when the value is null and zeroIsValid is false', () => {
    const value = null;
    const result = checkIfNull(value, false);
    expect(result).toBe(DEFAULT_ERROR_STRING);
  });

  // Returns '-' if value is undefined and zeroIsValid is false
  it('should return "-" when the value is undefined and zeroIsValid is false', () => {
    const value = undefined;
    const result = checkIfNull(value, false);
    expect(result).toBe(DEFAULT_ERROR_STRING);
  });

  // Returns '-' if value is an empty string and zeroIsValid is false
  it('should return "-" when the value is an empty string and zeroIsValid is false', () => {
    const value = '';
    const result = checkIfNull(value, false);
    expect(result).toBe(DEFAULT_ERROR_STRING);
  });

  // Returns the value if it is not null and zeroIsValid is true, even if it is 0
  it('should return the value when it is not null and zeroIsValid is true, even if it is 0', () => {
    const value = 0;
    const result = checkIfNull(value, true);
    expect(result).toBe(value);
  });
});

// Generated by CodiumAI

describe('bankAccountNumberSanitizer', () => {
  // Should return last 4 digits of a bank account number
  it('should return last 4 digits of a bank account number', () => {
    const result = bankAccountNumberSanitizer('123456789');
    expect(result).toBe('6789');
  });

  // Should return undefined when accountNum is undefined or undefined
  it('should return undefined when accountNum is undefined', () => {
    const result = bankAccountNumberSanitizer(undefined);
    expect(result).toBeUndefined();
  });

  // Should return last 3 digits when accountNum length is less than or equal to 4
  it('should return last 3 digits when accountNum length is less than or equal to 4', () => {
    const result = bankAccountNumberSanitizer('123');
    expect(result).toBe('123');
  });
});

describe('allowedAnnualWithdrawals', () => {
  // Returns 12 if policyStatus is ACTIVE or PENDINGLAPSE, accountValues.surrenderValue and accountValues.beginningAccountValue are greater than 0, and allocation.matchSegment.matchVestingDate is in the past
  it('should return 12 when all eligibility checks pass and matchVestingDate is in the past', () => {
    const policy: Policy = {
      policyStatus: PolicyStatus.ACTIVE,
      accountValues: {
        surrenderValue: 1000,
        beginningAccountValue: 2000,
      },
      allocation: {
        matchSegment: {
          matchVestingDate: dayjs().subtract(1, 'year').toISOString(),
        },
      },
      withdrawalValues: {
        maximumWithdrawalRequestAfterVestingPeriod: 12,
        maximumWithdrawalRequestDuringVestingPeriod: 1,
      },
    };

    const result = allowedAnnualWithdrawals(policy);

    expect(result).toBe(
      policy.withdrawalValues?.maximumWithdrawalRequestAfterVestingPeriod
    );
  });

  // Returns null if any of the eligibility checks fail
  it('should return null when any of the eligibility checks fail', () => {
    const policy: Policy = {
      policyStatus: PolicyStatus.ACTIVE,
      accountValues: {
        surrenderValue: 0,
        beginningAccountValue: 1000,
      },
      allocation: {
        matchSegment: {
          matchVestingDate: '2022-01-01',
        },
      },
    };

    const result = allowedAnnualWithdrawals(policy);

    expect(result).toBeNull();
  });

  // Returns null if policyStatus is undefined
  it('should return null when policyStatus is undefined', () => {
    const policy: Policy = {
      policyStatus: undefined,
      accountValues: {
        surrenderValue: 1000,
        beginningAccountValue: 2000,
      },
      allocation: {
        matchSegment: {
          matchVestingDate: dayjs().subtract(1, 'year').toISOString(),
        },
      },
    };

    const result = allowedAnnualWithdrawals(policy);

    expect(result).toBeNull();
  });

  // Returns null if accountValues is undefined
  it('should return null when accountValues is undefined', () => {
    const policy: Policy = {
      policyStatus: PolicyStatus.ACTIVE,
      accountValues: undefined,
      allocation: {
        matchSegment: {
          matchVestingDate: dayjs().subtract(1, 'year').toISOString(),
        },
      },
    };

    const result = allowedAnnualWithdrawals(policy);

    expect(result).toBeNull();
  });

  // Returns null if allocation is undefined
  it('should return null when allocation is undefined', () => {
    const policy: Policy = {
      policyStatus: PolicyStatus.ACTIVE,
      accountValues: {
        surrenderValue: 1000,
        beginningAccountValue: 2000,
      },
      allocation: undefined,
    };

    const result = allowedAnnualWithdrawals(policy);

    expect(result).toBeNull();
  });

  // Returns null if accountValues.surrenderValue is 0
  it('should return null when accountValues.surrenderValue is 0', () => {
    const policy: Policy = {
      policyStatus: PolicyStatus.ACTIVE,
      accountValues: {
        surrenderValue: 0,
        beginningAccountValue: 2000,
      },
      allocation: {
        matchSegment: {
          matchVestingDate: dayjs().subtract(1, 'year').toISOString(),
        },
      },
    };

    const result = allowedAnnualWithdrawals(policy);

    expect(result).toBeNull();
  });

  // Returns null if allocation.matchSegment.matchVestingDate is not defined
  it('should return null when allocation.matchSegment.matchVestingDate is not defined', () => {
    const policy: Policy = {
      policyStatus: PolicyStatus.ACTIVE,
      accountValues: {
        surrenderValue: 1000,
        beginningAccountValue: 2000,
      },
      allocation: {
        matchSegment: {},
      },
    };

    const result = allowedAnnualWithdrawals(policy);

    expect(result).toBeNull();
  });

  // Returns null if policyStatus is not ACTIVE or PENDINGLAPSE
  it('should return null when policyStatus is not ACTIVE or PENDINGLAPSE', () => {
    const policy: Policy = {
      policyStatus: PolicyStatus.SURRENDERED,
      accountValues: {
        surrenderValue: 1000,
        beginningAccountValue: 2000,
      },
      allocation: {
        matchSegment: {
          matchVestingDate: dayjs().subtract(1, 'year').toISOString(),
        },
      },
    };

    const result = allowedAnnualWithdrawals(policy);

    expect(result).toBeNull();
  });

  // Returns null if accountValues.surrenderValue is not greater than 0
  it('should return null when accountValues.surrenderValue is not greater than 0', () => {
    const policy: Policy = {
      policyStatus: PolicyStatus.ACTIVE,
      accountValues: {
        surrenderValue: 0,
        beginningAccountValue: 2000,
      },
      allocation: {
        matchSegment: {
          matchVestingDate: dayjs().subtract(1, 'year').toISOString(),
        },
      },
    };

    const result = allowedAnnualWithdrawals(policy);

    expect(result).toBeNull();
  });

  // Returns null if accountValues.beginningAccountValue is not greater than 0
  it('should return null when accountValues.beginningAccountValue is not greater than 0', () => {
    const policy: Policy = {
      policyStatus: PolicyStatus.ACTIVE,
      accountValues: {
        surrenderValue: 1000,
        beginningAccountValue: 0,
      },
      allocation: {
        matchSegment: {
          matchVestingDate: dayjs().subtract(1, 'year').toISOString(),
        },
      },
    };

    const result = allowedAnnualWithdrawals(policy);

    expect(result).toBeNull();
  });
});
