// Generated by CodiumAI

import { numberWithOrdinal } from './numbers';
import { DEFAULT_ERROR_STRING } from './strings';

describe('numberWithOrdinal', () => {
  // Returns the correct ordinal for numbers ending in 1, 2, and 3.
  it('should return the correct ordinal for numbers ending in 1', () => {
    // Arrange
    const value = 1;

    // Act
    const result = numberWithOrdinal(value);

    // Assert
    expect(result).toBe('1st');
  });

  // Returns the correct ordinal for numbers ending in 1, 2, and 3.
  it('should return the correct ordinal for numbers ending in 2', () => {
    // Arrange
    const value = 2;

    // Act
    const result = numberWithOrdinal(value);

    // Assert
    expect(result).toBe('2nd');
  });

  // Returns the correct ordinal for numbers ending in 1, 2, and 3.
  it('should return the correct ordinal for numbers ending in 3', () => {
    // Arrange
    const value = 3;

    // Act
    const result = numberWithOrdinal(value);

    // Assert
    expect(result).toBe('3rd');
  });

  // Returns the correct ordinal for the number 0.
  it('should return the correct ordinal for the number 0', () => {
    // Arrange
    const value = 0;

    // Act
    const result = numberWithOrdinal(value);

    // Assert
    expect(result).toBe(DEFAULT_ERROR_STRING);
  });

  // Returns the correct ordinal for the number 7.
  it('should return the correct ordinal for the number 7', () => {
    // Arrange
    const value = 7;

    // Act
    const result = numberWithOrdinal(value);

    // Assert
    expect(result).toBe('7th');
  });
});
