export const states = [
  { textValue: 'AL', label: 'Alabama', value: 'AL' },
  { textValue: 'AK', label: 'Alaska', value: 'AK' },
  { textValue: 'AZ', label: 'Arizona', value: 'AZ' },
  { textValue: 'AR', label: 'Arkansas', value: 'AR' },
  { textValue: 'CA', label: 'California', value: 'CA' },
  { textValue: 'CO', label: 'Colorado', value: 'CO' },
  { textValue: 'CT', label: 'Connecticut', value: 'CT' },
  { textValue: 'DC', label: 'District of Columbia', value: 'DC' },
  { textValue: 'DE', label: 'Delaware', value: 'DE' },
  { textValue: 'FL', label: 'Florida', value: 'FL' },
  { textValue: 'GA', label: 'Georgia', value: 'GA' },
  { textValue: 'HI', label: 'Hawaii', value: 'HI' },
  { textValue: 'ID', label: 'Idaho', value: 'ID' },
  { textValue: 'IL', label: 'Illinois', value: 'IL' },
  { textValue: 'IN', label: 'Indiana', value: 'IN' },
  { textValue: 'IA', label: 'Iowa', value: 'IA' },
  { textValue: 'KS', label: 'Kansas', value: 'KS' },
  { textValue: 'KY', label: 'Kentucky', value: 'KY' },
  { textValue: 'LA', label: 'Louisiana', value: 'LA' },
  { textValue: 'ME', label: 'Maine', value: 'ME' },
  { textValue: 'MD', label: 'Maryland', value: 'MD' },
  { textValue: 'MA', label: 'Massachusetts', value: 'MA' },
  { textValue: 'MI', label: 'Michigan', value: 'MI' },
  { textValue: 'MN', label: 'Minnesota', value: 'MN' },
  { textValue: 'MS', label: 'Mississippi', value: 'MS' },
  { textValue: 'MO', label: 'Missouri', value: 'MO' },
  { textValue: 'MT', label: 'Montana', value: 'MT' },
  { textValue: 'NE', label: 'Nebraska', value: 'NE' },
  { textValue: 'NV', label: 'Nevada', value: 'NV' },
  { textValue: 'NH', label: 'New Hampshire', value: 'NH' },
  { textValue: 'NJ', label: 'New Jersey', value: 'NJ' },
  { textValue: 'NM', label: 'New Mexico', value: 'NM' },
  { textValue: 'NY', label: 'New York', value: 'NY' },
  { textValue: 'NC', label: 'North Carolina', value: 'NC' },
  { textValue: 'ND', label: 'North Dakota', value: 'ND' },
  { textValue: 'OH', label: 'Ohio', value: 'OH' },
  { textValue: 'OK', label: 'Oklahoma', value: 'OK' },
  { textValue: 'OR', label: 'Oregon', value: 'OR' },
  { textValue: 'PA', label: 'Pennsylvania', value: 'PA' },
  { textValue: 'RI', label: 'Rhode Island', value: 'RI' },
  { textValue: 'SC', label: 'South Carolina', value: 'SC' },
  { textValue: 'SD', label: 'South Dakota', value: 'SD' },
  { textValue: 'TN', label: 'Tennessee', value: 'TN' },
  { textValue: 'TX', label: 'Texas', value: 'TX' },
  { textValue: 'UT', label: 'Utah', value: 'UT' },
  { textValue: 'VT', label: 'Vermont', value: 'VT' },
  { textValue: 'VA', label: 'Virginia', value: 'VA' },
  { textValue: 'WA', label: 'Washington', value: 'WA' },
  { textValue: 'WV', label: 'West Virginia', value: 'WV' },
  { textValue: 'WI', label: 'Wisconsin', value: 'WI' },
  { textValue: 'WY', label: 'Wyoming', value: 'WY' },
];
