// Generated by CodiumAI

import {
  DEFAULT_ERROR_STRING,
  toSentenceCase,
  toTitleCase,
  pluralize,
  createQueryString,
  indefiniteArticle,
  formatPhoneNumber,
} from './strings';

describe('toTitleCase', () => {
  describe('a string with multiple words', () => {
    it("should return string with each word's first letter capitalized ", () => {
      const result = toTitleCase('this is a sentence');
      expect(result).toEqual('This Is A Sentence');
    });
  });

  it('should return an empty string when input is undefined', () => {
    const result = toTitleCase(undefined);
    expect(result).toEqual('');
  });

  it('should return an empty string when input is an empty string', () => {
    const result = toTitleCase('');
    expect(result).toEqual('');
  });
});

describe('toSentenceCase', () => {
  describe('a string with multiple words', () => {
    it('should return string with only the first letter capitalized ', () => {
      const result = toSentenceCase('this is a sentence');
      expect(result).toEqual('This is a sentence');
    });
  });

  it('should return an empty string when input is undefined', () => {
    const result = toSentenceCase(undefined);
    expect(result).toEqual(DEFAULT_ERROR_STRING);
  });

  it('should return an empty string when input is an empty string', () => {
    const result = toSentenceCase('');
    expect(result).toEqual(DEFAULT_ERROR_STRING);
  });
});

// Generated by CodiumAI

describe('pluralize', () => {
  // Returns the plural form of a given string when quantity is greater than 1
  it('should return the plural form of a given string when quantity is greater than 1', () => {
    const result = pluralize(2, 'apple');
    expect(result).toBe('2 apples');
  });

  // Returns the plural form of a given string when quantity is 0
  it('should return the plural form of a given string when quantity is 0', () => {
    const result = pluralize(0, 'apple');
    expect(result).toBe('0 apples');
  });

  // Returns the singular form of a given string when quantity is 1
  it('should return the plural form of a given string when quantity is 0', () => {
    const result = pluralize(1, 'apple');
    expect(result).toBe('1 apple');
  });

  // Returns only the value of the word when wordOnly is true
  it('should return the plural form of a given string when quantity is 0', () => {
    const result = pluralize(1, 'apple', true);
    expect(result).toBe('apple');
  });
});

describe('createQueryString', () => {
  it('should return an empty string if given an empty object', () => {
    expect(createQueryString({})).toBe('');
  });

  it('should return a query string from a given object', () => {
    const obj = { foo: 'bar', baz: 'qux' };
    const queryString = createQueryString(obj);
    expect(queryString).toBe('foo=bar&baz=qux');
  });

  it('should handle objects with multiple key-value pairs', () => {
    const obj = { foo: 'bar', baz: 'qux', quux: 'corge' };
    const queryString = createQueryString(obj);
    expect(queryString).toBe('foo=bar&baz=qux&quux=corge');
  });

  it('should handle objects with non-string values', () => {
    const obj = { foo: 123, baz: true };
    const queryString = createQueryString(obj);
    expect(queryString).toBe('foo=123&baz=true');
  });
});

describe('indefiniteArticle', () => {
  it('should return an empty string when word is undefined', () => {
    expect(indefiniteArticle(undefined)).toBe('');
  });

  it('should return an empty string when word is an empty string', () => {
    expect(indefiniteArticle('')).toBe('');
  });

  it('should return "an" when the word starts with a vowel', () => {
    expect(indefiniteArticle('elephant')).toBe('an');
    expect(indefiniteArticle('Aardvark')).toBe('an');
  });

  it('should return "a" when the word starts with a non-vowel', () => {
    expect(indefiniteArticle('tiger')).toBe('a');
    expect(indefiniteArticle('123')).toBe('a');
  });
});

// Unit tests for formatPhoneNumber function
describe('formatPhoneNumber', () => {
  test('formats phone number with country code, area code, and rest of the phone number', () => {
    const input = '18673452345';
    const expectedOutput = '1-867-345-2345';
    expect(formatPhoneNumber(input)).toBe(expectedOutput);
  });

  test('formats phone number with country code including "+"', () => {
    const input = '+18673452345';
    const expectedOutput = '+1-867-345-2345';
    expect(formatPhoneNumber(input)).toBe(expectedOutput);
  });

  test('formats phone number with area code and rest of the phone number', () => {
    const input = '8673452345';
    const expectedOutput = '867-345-2345';
    expect(formatPhoneNumber(input)).toBe(expectedOutput);
  });

  test('formats phone number with only the rest of the phone number', () => {
    const input = '3452345';
    const expectedOutput = '345-2345';
    expect(formatPhoneNumber(input)).toBe(expectedOutput);
  });

  test('returns the original input for invalid phone number format', () => {
    const input = '12345';
    const expectedOutput = '12345';
    expect(formatPhoneNumber(input)).toBe(expectedOutput);
  });

  test('returns the original input for empty string', () => {
    const input = '';
    const expectedOutput = '';
    expect(formatPhoneNumber(input)).toBe(expectedOutput);
  });

  test('returns the original input for non-numeric characters', () => {
    const input = 'abc12345';
    const expectedOutput = 'abc12345';
    expect(formatPhoneNumber(input)).toBe(expectedOutput);
  });

  test('returns the original input for mixed format', () => {
    const input = '12-345-6789';
    const expectedOutput = '12-345-6789';
    expect(formatPhoneNumber(input)).toBe(expectedOutput);
  });

  test('returns properly formatted number without country code and area code', () => {
    const input = '1234567890';
    const expectedOutput = '123-456-7890';
    expect(formatPhoneNumber(input)).toBe(expectedOutput);
  });
});
