// Generated by CodiumAI

import {
  DEFAULT_ERROR_STRING,
  toSentenceCase,
  toTitleCase,
  pluralize,
} from './strings';

describe('toTitleCase', () => {
  describe('a string with multiple words', () => {
    it("should return string with each word's first letter capitalized ", () => {
      const result = toTitleCase('this is a sentence');
      expect(result).toEqual('This Is A Sentence');
    });
  });

  it('should return an empty string when input is undefined', () => {
    const result = toTitleCase(undefined);
    expect(result).toEqual('');
  });

  it('should return an empty string when input is an empty string', () => {
    const result = toTitleCase('');
    expect(result).toEqual('');
  });
});

describe('toSentenceCase', () => {
  describe('a string with multiple words', () => {
    it('should return string with only the first letter capitalized ', () => {
      const result = toSentenceCase('this is a sentence');
      expect(result).toEqual('This is a sentence');
    });
  });

  it('should return an empty string when input is undefined', () => {
    const result = toSentenceCase(undefined);
    expect(result).toEqual(DEFAULT_ERROR_STRING);
  });

  it('should return an empty string when input is an empty string', () => {
    const result = toSentenceCase('');
    expect(result).toEqual(DEFAULT_ERROR_STRING);
  });
});

// Generated by CodiumAI

describe('pluralize', () => {
  // Returns the plural form of a given string when quantity is greater than 1
  it('should return the plural form of a given string when quantity is greater than 1', () => {
    const result = pluralize(2, 'apple');
    expect(result).toBe('2 apples');
  });

  // Returns the plural form of a given string when quantity is 0
  it('should return the plural form of a given string when quantity is 0', () => {
    const result = pluralize(0, 'apple');
    expect(result).toBe('0 apples');
  });

  // Returns the singular form of a given string when quantity is 1
  it('should return the plural form of a given string when quantity is 0', () => {
    const result = pluralize(1, 'apple');
    expect(result).toBe('1 apple');
  });

  // Returns only the value of the word when wordOnly is true
  it('should return the plural form of a given string when quantity is 0', () => {
    const result = pluralize(1, 'apple', true);
    expect(result).toBe('apple');
  });
});
