import { TaskType } from '@deps/models/case/task';

export const allowedTaskTypes = new Set<TaskType>([
    TaskType.Agent_Review,
    TaskType.PURCHASE_DOCUMENT_MATCHING,
    TaskType.Standard_Document_Matching,
    TaskType.Review_Ofac,
    TaskType.Agent_Onboarding_Review,
    TaskType.TOA_Review,
    TaskType.Prenote_Review,
    TaskType.Payment_Processing_Review,
    TaskType.Application_Review,
    TaskType.Agent_Onboarding_Review,
    TaskType.Cost_Basis_Review,
    TaskType.Claims_Fi_Escheatment_Task,
    TaskType.Default_Case_DataEntry,
    TaskType.Claims_Identify_Uncashed_Transactions,
    TaskType.Claims_Stop_Uncashed_Transactions,
    TaskType.Claims_Reverse_Uncashed_Transactions,
    TaskType.Background_Review,
    TaskType.Bene_Address_Verification,
    TaskType.Bene_Call,
    TaskType.Payment_Follow_Up,
    TaskType.Ops_Review,
    TaskType.Day_150_Review,
    TaskType.Policyupdate_Partydetails_Review,
    TaskType.Initiate_Postissue_Transaction,
    TaskType.Initiate_BeneChange_Transaction,
]);
