import {
    SegmentTransactionType,
    TransactionArea,
    TransactionCategory,
    TransactionMode,
    TransactionSubmittedEventType,
    TransactionSuccessfulEvent,
    UI_SURFACE,
} from '@deps/types/segment-analytics';

// BPB - process.env isn't *technically* a constant, but cut me some slack, ok?
export const EventConfig: {
    [key in TransactionSubmittedEventType]: Pick<
        TransactionSuccessfulEvent,
        | 'area'
        | 'category'
        | 'environment'
        | 'mode'
        | 'transaction_key'
        | 'type'
        | 'ui_surface'
    >;
} = {
    [TransactionSubmittedEventType.ONE_TIME_PREMIUM]: {
        area: TransactionArea.PAYMENTS,
        category: TransactionCategory.FINANCIAL,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.ONE_TIME,
        transaction_key: `${TransactionCategory.FINANCIAL}:${SegmentTransactionType.PREMIUM}:${TransactionMode.ONE_TIME}`,
        type: SegmentTransactionType.PREMIUM,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.SYSTEMATIC_PAYMENT_SETUP]: {
        area: TransactionArea.PAYMENTS,
        category: TransactionCategory.FINANCIAL,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.AUTOPAY_SETUP,
        transaction_key: `${TransactionCategory.FINANCIAL}:${SegmentTransactionType.PREMIUM}:${TransactionMode.AUTOPAY_SETUP}`,
        type: SegmentTransactionType.PREMIUM,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.SYSTEMATIC_PAYMENT_UPDATE]: {
        area: TransactionArea.PAYMENTS,
        category: TransactionCategory.FINANCIAL,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.AUTOPAY_MANAGE,
        transaction_key: `${TransactionCategory.FINANCIAL}:${SegmentTransactionType.PREMIUM}:${TransactionMode.AUTOPAY_MANAGE}`,
        type: SegmentTransactionType.PREMIUM,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.SYSTEMATIC_PAYMENT_CANCEL]: {
        area: TransactionArea.PAYMENTS,
        category: TransactionCategory.FINANCIAL,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.AUTOPAY_CANCEL,
        transaction_key: `${TransactionCategory.FINANCIAL}:${SegmentTransactionType.PREMIUM}:${TransactionMode.AUTOPAY_CANCEL}`,
        type: SegmentTransactionType.PREMIUM,
        ui_surface: UI_SURFACE.SIDE_PANEL,
    },
    [TransactionSubmittedEventType.ONE_TIME_LOAN]: {
        area: TransactionArea.PAYMENTS,
        category: TransactionCategory.FINANCIAL,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.ONE_TIME,
        transaction_key: `${TransactionCategory.FINANCIAL}:${SegmentTransactionType.LOAN}:${TransactionMode.ONE_TIME}`,
        type: SegmentTransactionType.LOAN,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.SYSTEMATIC_LOAN_SETUP]: {
        area: TransactionArea.PAYMENTS,
        category: TransactionCategory.FINANCIAL,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.AUTOPAY_SETUP,
        transaction_key: `${TransactionCategory.FINANCIAL}:${SegmentTransactionType.LOAN}:${TransactionMode.AUTOPAY_SETUP}`,
        type: SegmentTransactionType.LOAN,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.SYSTEMATIC_LOAN_UPDATE]: {
        area: TransactionArea.PAYMENTS,
        category: TransactionCategory.FINANCIAL,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.AUTOPAY_MANAGE,
        transaction_key: `${TransactionCategory.FINANCIAL}:${SegmentTransactionType.LOAN}:${TransactionMode.AUTOPAY_MANAGE}`,
        type: SegmentTransactionType.LOAN,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.SYSTEMATIC_LOAN_CANCEL]: {
        area: TransactionArea.PAYMENTS,
        category: TransactionCategory.FINANCIAL,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.AUTOPAY_CANCEL,
        transaction_key: `${TransactionCategory.FINANCIAL}:${SegmentTransactionType.LOAN}:${TransactionMode.AUTOPAY_CANCEL}`,
        type: SegmentTransactionType.LOAN,
        ui_surface: UI_SURFACE.SIDE_PANEL,
    },
    [TransactionSubmittedEventType.ONE_TIME_WITHDRAWAL]: {
        area: TransactionArea.DISBURSEMENTS,
        category: TransactionCategory.FINANCIAL,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.ONE_TIME,
        transaction_key: `${TransactionCategory.FINANCIAL}:${SegmentTransactionType.WITHDRAWAL}:${TransactionMode.ONE_TIME}`,
        type: SegmentTransactionType.WITHDRAWAL,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.SYSTEMATIC_WITHDRAWAL_SETUP]: {
        area: TransactionArea.DISBURSEMENTS,
        category: TransactionCategory.FINANCIAL,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.AUTOPAY_SETUP,
        transaction_key: `${TransactionCategory.FINANCIAL}:${SegmentTransactionType.WITHDRAWAL}:${TransactionMode.AUTOPAY_SETUP}`,
        type: SegmentTransactionType.WITHDRAWAL,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.SYSTEMATIC_WITHDRAWAL_UPDATE]: {
        area: TransactionArea.DISBURSEMENTS,
        category: TransactionCategory.FINANCIAL,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.AUTOPAY_MANAGE,
        transaction_key: `${TransactionCategory.FINANCIAL}:${SegmentTransactionType.WITHDRAWAL}:${TransactionMode.AUTOPAY_MANAGE}`,
        type: SegmentTransactionType.WITHDRAWAL,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.SYSTEMATIC_WITHDRAWAL_CANCEL]: {
        area: TransactionArea.DISBURSEMENTS,
        category: TransactionCategory.FINANCIAL,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.AUTOPAY_CANCEL,
        transaction_key: `${TransactionCategory.FINANCIAL}:${SegmentTransactionType.WITHDRAWAL}:${TransactionMode.AUTOPAY_CANCEL}`,
        type: SegmentTransactionType.WITHDRAWAL,
        ui_surface: UI_SURFACE.SIDE_PANEL,
    },
    [TransactionSubmittedEventType.ONE_TIME_RMD]: {
        area: TransactionArea.DISBURSEMENTS,
        category: TransactionCategory.FINANCIAL,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.ONE_TIME,
        transaction_key: `${TransactionCategory.FINANCIAL}:${SegmentTransactionType.RMD}:${TransactionMode.ONE_TIME}`,
        type: SegmentTransactionType.RMD,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.SYSTEMATIC_RMD_SETUP]: {
        area: TransactionArea.DISBURSEMENTS,
        category: TransactionCategory.FINANCIAL,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.AUTOPAY_SETUP,
        transaction_key: `${TransactionCategory.FINANCIAL}:${SegmentTransactionType.RMD}:${TransactionMode.AUTOPAY_SETUP}`,
        type: SegmentTransactionType.RMD,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.SYSTEMATIC_RMD_UPDATE]: {
        area: TransactionArea.DISBURSEMENTS,
        category: TransactionCategory.FINANCIAL,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.AUTOPAY_MANAGE,
        transaction_key: `${TransactionCategory.FINANCIAL}:${SegmentTransactionType.RMD}:${TransactionMode.AUTOPAY_MANAGE}`,
        type: SegmentTransactionType.RMD,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.SYSTEMATIC_RMD_CANCEL]: {
        area: TransactionArea.DISBURSEMENTS,
        category: TransactionCategory.FINANCIAL,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.AUTOPAY_CANCEL,
        transaction_key: `${TransactionCategory.FINANCIAL}:${SegmentTransactionType.RMD}:${TransactionMode.AUTOPAY_CANCEL}`,
        type: SegmentTransactionType.RMD,
        ui_surface: UI_SURFACE.SIDE_PANEL,
    },
    [TransactionSubmittedEventType.SURRENDER]: {
        area: TransactionArea.DISBURSEMENTS,
        category: TransactionCategory.FINANCIAL,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.REQUEST,
        transaction_key: `${TransactionCategory.FINANCIAL}:${SegmentTransactionType.SURRENDER}:${TransactionMode.REQUEST}`,
        type: SegmentTransactionType.SURRENDER,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.DEATH_CLAIM]: {
        area: TransactionArea.POLICIES_CONTRACTS,
        category: TransactionCategory.NON_FINANCIAL,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.REQUEST,
        transaction_key: `${TransactionCategory.NON_FINANCIAL}:${SegmentTransactionType.DEATH_CLAIM}:${TransactionMode.REQUEST}`,
        type: SegmentTransactionType.DEATH_CLAIM,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.NEW_LOAN]: {
        area: TransactionArea.DISBURSEMENTS,
        category: TransactionCategory.FINANCIAL,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.REQUEST,
        transaction_key: `${TransactionCategory.FINANCIAL}:${SegmentTransactionType.NEW_LOAN}:${TransactionMode.REQUEST}`,
        type: SegmentTransactionType.NEW_LOAN,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.EDIT_ALLOCATIONS]: {
        area: TransactionArea.FUNDS_ACCOUNTS,
        category: TransactionCategory.NON_FINANCIAL,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.CHANGE,
        transaction_key: `${TransactionCategory.NON_FINANCIAL}:${SegmentTransactionType.ALLOCATIONS}:${TransactionMode.CHANGE}`,
        type: SegmentTransactionType.ALLOCATIONS,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.FREE_LOOK_CANCELLATION]: {
        area: TransactionArea.POLICIES_CONTRACTS,
        category: TransactionCategory.NON_FINANCIAL,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.CANCELLATION,
        transaction_key: `${TransactionCategory.NON_FINANCIAL}:${SegmentTransactionType.FREE_LOOK_CANCELLATION}:${TransactionMode.CANCELLATION}`,
        type: SegmentTransactionType.FREE_LOOK_CANCELLATION,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.FUND_TRANSFER]: {
        area: TransactionArea.FUNDS_ACCOUNTS,
        category: TransactionCategory.NON_FINANCIAL,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.CHANGE,
        transaction_key: `${TransactionCategory.NON_FINANCIAL}:${SegmentTransactionType.FUND_TRANSFER}:${TransactionMode.CHANGE}`,
        type: SegmentTransactionType.FUND_TRANSFER,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.ADD_ADDRESS]: {
        area: TransactionArea.PEOPLE,
        category: TransactionCategory.POLICY_UPDATE,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.ADD,
        transaction_key: `${TransactionCategory.POLICY_UPDATE}:${SegmentTransactionType.ADDRESS}:${TransactionMode.ADD}`,
        type: SegmentTransactionType.ADDRESS,
        ui_surface: UI_SURFACE.SIDE_PANEL,
    },
    [TransactionSubmittedEventType.UPDATE_ADDRESS]: {
        area: TransactionArea.PEOPLE,
        category: TransactionCategory.POLICY_UPDATE,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.CHANGE,
        transaction_key: `${TransactionCategory.POLICY_UPDATE}:${SegmentTransactionType.ADDRESS}:${TransactionMode.CHANGE}`,
        type: SegmentTransactionType.ADDRESS,
        ui_surface: UI_SURFACE.SIDE_PANEL,
    },
    [TransactionSubmittedEventType.REMOVE_ADDRESS]: {
        area: TransactionArea.PEOPLE,
        category: TransactionCategory.POLICY_UPDATE,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.REMOVE,
        transaction_key: `${TransactionCategory.POLICY_UPDATE}:${SegmentTransactionType.ADDRESS}:${TransactionMode.REMOVE}`,
        type: SegmentTransactionType.ADDRESS,
        ui_surface: UI_SURFACE.SIDE_PANEL,
    },
    [TransactionSubmittedEventType.ADD_EMAIL]: {
        area: TransactionArea.PEOPLE,
        category: TransactionCategory.POLICY_UPDATE,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.ADD,
        transaction_key: `${TransactionCategory.POLICY_UPDATE}:${SegmentTransactionType.EMAIL}:${TransactionMode.ADD}`,
        type: SegmentTransactionType.EMAIL,
        ui_surface: UI_SURFACE.SIDE_PANEL,
    },
    [TransactionSubmittedEventType.UPDATE_EMAIL]: {
        area: TransactionArea.PEOPLE,
        category: TransactionCategory.POLICY_UPDATE,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.CHANGE,
        transaction_key: `${TransactionCategory.POLICY_UPDATE}:${SegmentTransactionType.EMAIL}:${TransactionMode.CHANGE}`,
        type: SegmentTransactionType.EMAIL,
        ui_surface: UI_SURFACE.SIDE_PANEL,
    },
    [TransactionSubmittedEventType.REMOVE_EMAIL]: {
        area: TransactionArea.PEOPLE,
        category: TransactionCategory.POLICY_UPDATE,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.REMOVE,
        transaction_key: `${TransactionCategory.POLICY_UPDATE}:${SegmentTransactionType.EMAIL}:${TransactionMode.REMOVE}`,
        type: SegmentTransactionType.EMAIL,
        ui_surface: UI_SURFACE.SIDE_PANEL,
    },
    [TransactionSubmittedEventType.ADD_PHONE]: {
        area: TransactionArea.PEOPLE,
        category: TransactionCategory.POLICY_UPDATE,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.ADD,
        transaction_key: `${TransactionCategory.POLICY_UPDATE}:${SegmentTransactionType.PHONE}:${TransactionMode.ADD}`,
        type: SegmentTransactionType.PHONE,
        ui_surface: UI_SURFACE.SIDE_PANEL,
    },
    [TransactionSubmittedEventType.UPDATE_PHONE]: {
        area: TransactionArea.PEOPLE,
        category: TransactionCategory.POLICY_UPDATE,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.CHANGE,
        transaction_key: `${TransactionCategory.POLICY_UPDATE}:${SegmentTransactionType.PHONE}:${TransactionMode.CHANGE}`,
        type: SegmentTransactionType.PHONE,
        ui_surface: UI_SURFACE.SIDE_PANEL,
    },
    [TransactionSubmittedEventType.REMOVE_PHONE]: {
        area: TransactionArea.PEOPLE,
        category: TransactionCategory.POLICY_UPDATE,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.REMOVE,
        transaction_key: `${TransactionCategory.POLICY_UPDATE}:${SegmentTransactionType.PHONE}:${TransactionMode.REMOVE}`,
        type: SegmentTransactionType.PHONE,
        ui_surface: UI_SURFACE.SIDE_PANEL,
    },
    [TransactionSubmittedEventType.ADD_BANK_INFO]: {
        area: TransactionArea.PEOPLE,
        category: TransactionCategory.POLICY_UPDATE,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.ADD,
        transaction_key: `${TransactionCategory.POLICY_UPDATE}:${SegmentTransactionType.BANK_INFO}:${TransactionMode.ADD}`,
        type: SegmentTransactionType.BANK_INFO,
        ui_surface: UI_SURFACE.SIDE_PANEL,
    },
    [TransactionSubmittedEventType.UPDATE_BANK_INFO]: {
        area: TransactionArea.PEOPLE,
        category: TransactionCategory.POLICY_UPDATE,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.CHANGE,
        transaction_key: `${TransactionCategory.POLICY_UPDATE}:${SegmentTransactionType.BANK_INFO}:${TransactionMode.CHANGE}`,
        type: SegmentTransactionType.BANK_INFO,
        ui_surface: UI_SURFACE.SIDE_PANEL,
    },
    [TransactionSubmittedEventType.REMOVE_BANK_INFO]: {
        area: TransactionArea.PEOPLE,
        category: TransactionCategory.POLICY_UPDATE,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.REMOVE,
        transaction_key: `${TransactionCategory.POLICY_UPDATE}:${SegmentTransactionType.BANK_INFO}:${TransactionMode.REMOVE}`,
        type: SegmentTransactionType.BANK_INFO,
        ui_surface: UI_SURFACE.SIDE_PANEL,
    },
    [TransactionSubmittedEventType.UPDATE_BENEFICIARIES]: {
        area: TransactionArea.PEOPLE,
        category: TransactionCategory.POLICY_UPDATE,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.CHANGE,
        transaction_key: `${TransactionCategory.POLICY_UPDATE}:${SegmentTransactionType.BENEFICIARY}:${TransactionMode.CHANGE}`,
        type: SegmentTransactionType.BENEFICIARY,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.UPDATE_COMMUNICATION_PREFERENCE]: {
        area: TransactionArea.PEOPLE,
        category: TransactionCategory.POLICY_UPDATE,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.CHANGE,
        transaction_key: `${TransactionCategory.POLICY_UPDATE}:${SegmentTransactionType.COMMUNICATION_PREFERENCE}:${TransactionMode.CHANGE}`,
        type: SegmentTransactionType.COMMUNICATION_PREFERENCE,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.UPDATE_NAME]: {
        area: TransactionArea.PEOPLE,
        category: TransactionCategory.POLICY_UPDATE,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.CHANGE,
        transaction_key: `${TransactionCategory.POLICY_UPDATE}:${SegmentTransactionType.NAME}:${TransactionMode.CHANGE}`,
        type: SegmentTransactionType.NAME,
        ui_surface: UI_SURFACE.SIDE_PANEL,
    },
    [TransactionSubmittedEventType.UPDATE_OWNER]: {
        area: TransactionArea.PEOPLE,
        category: TransactionCategory.POLICY_UPDATE,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.CHANGE,
        transaction_key: `${TransactionCategory.POLICY_UPDATE}:${SegmentTransactionType.OWNER}:${TransactionMode.CHANGE}`,
        type: SegmentTransactionType.OWNER,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.UPDATE_JOINT_OWNER]: {
        area: TransactionArea.PEOPLE,
        category: TransactionCategory.POLICY_UPDATE,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.CHANGE,
        transaction_key: `${TransactionCategory.POLICY_UPDATE}:${SegmentTransactionType.JOINT_OWNER}:${TransactionMode.CHANGE}`,
        type: SegmentTransactionType.JOINT_OWNER,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.ADD_PAYOR]: {
        area: TransactionArea.PEOPLE,
        category: TransactionCategory.POLICY_UPDATE,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.ADD,
        transaction_key: `${TransactionCategory.POLICY_UPDATE}:${SegmentTransactionType.PAYOR}:${TransactionMode.ADD}`,
        type: SegmentTransactionType.PAYOR,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.REMOVE_PAYOR]: {
        area: TransactionArea.PEOPLE,
        category: TransactionCategory.POLICY_UPDATE,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.REMOVE,
        transaction_key: `${TransactionCategory.POLICY_UPDATE}:${SegmentTransactionType.PAYOR}:${TransactionMode.REMOVE}`,
        type: SegmentTransactionType.PAYOR,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.ADD_THIRD_PARTY]: {
        area: TransactionArea.PEOPLE,
        category: TransactionCategory.POLICY_UPDATE,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.ADD,
        transaction_key: `${TransactionCategory.POLICY_UPDATE}:${SegmentTransactionType.THIRD_PARTY}:${TransactionMode.ADD}`,
        type: SegmentTransactionType.THIRD_PARTY,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.REMOVE_THIRD_PARTY]: {
        area: TransactionArea.PEOPLE,
        category: TransactionCategory.POLICY_UPDATE,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.REMOVE,
        transaction_key: `${TransactionCategory.POLICY_UPDATE}:${SegmentTransactionType.THIRD_PARTY}:${TransactionMode.REMOVE}`,
        type: SegmentTransactionType.THIRD_PARTY,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.ADD_ASSIGNEE]: {
        area: TransactionArea.PEOPLE,
        category: TransactionCategory.POLICY_UPDATE,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.ADD,
        transaction_key: `${TransactionCategory.POLICY_UPDATE}:${SegmentTransactionType.ASSIGNEE}:${TransactionMode.ADD}`,
        type: SegmentTransactionType.ASSIGNEE,
        ui_surface: UI_SURFACE.FLOW,
    },
    [TransactionSubmittedEventType.ADD_ANNUITANT]: {
        area: TransactionArea.PEOPLE,
        category: TransactionCategory.POLICY_UPDATE,
        environment: process.env.NODE_ENV,
        mode: TransactionMode.ADD,
        transaction_key: `${TransactionCategory.POLICY_UPDATE}:${SegmentTransactionType.ANNUITANT}:${TransactionMode.ADD}`,
        type: SegmentTransactionType.ANNUITANT,
        ui_surface: UI_SURFACE.FLOW,
    },
};
