export enum FEATURE_FLAGS {
  ADD_EDIT_DELETE_BANK_ACCOUNT = 'add_edit_delete_bank_account',
  AMP_TRANSACTION_SUMMARY = 'amp_transaction_summary',
  ANNUITY_MODE = 'annuity_mode',
  ADD_EDIT_DELETE_ADDRESS = 'add_edit_delete_address',
  DOCUMENTS_V3 = 'documents-v3-update',
  TRANSACTION_LEVEL_CODE_ADD_BANK = 'transaction_level_code_add_bank',
  COMMUNICATION_PREFERENCES = 'communication_preferences',
  TRANSACTION_NOTIFICATIONS = 'transaction_notifications',
  POLICY_OWNER_PROFILE_PARTIES = 'policy_owner_profile_parties',
  FARMERS_PAYMENTUS = 'farmers_paymentus',
  TRANSACTION_PARTIAL_WITHDRAWAL_ONETIME = 'transaction_partial_withdrawal_onetime',
  TRANSACTION_SYSTEMATIC_PREMIUM = 'transaction_systematic_premium',
  WELLABE_AUTH_TOKENS = 'wellabe_auth_tokens',
  ENTERPRISE_POLICY_SEARCH = 'enterprise_policy_search',
  ENTERPRISE_CASE_SEARCH = 'enterprise_case_search',
  TRANSACTION_FULL_SURRENDER = 'transaction_full_surrender',
  EVERLY_CHILD_RIDER = 'everly_child_rider',
  UPDATED_TRANSACTION_URL = 'updated_transaction_url',
  PAYMENT_METHODS_API = 'payment_methods_api',
  TRANSACTION_FREE_LOOK_CANCEL = 'transaction_free_look_cancel',
  NOTIFICATION_ALERT_BANNER = 'notification_alert_banner',
}
