// Generated by CodiumAI

import { fireEvent, render } from '@testing-library/react';
import dayjs from 'dayjs';

import {
  SelectAmount,
  dateInvalidMessage,
  dateOutOfRangeMessage,
} from './SelectAmount';

// Mock useRouter:
jest.mock("next/navigation", () => ({
  useRouter() {
    return {
      prefetch: () => null
    };
  }
}));

describe('SelectAmount', () => {
  // Date within valid range moves to next step
  it('should move to next step when date is within valid range', () => {
    const moveToNextStep = jest.fn();
    const { getByLabelText, getByText } = render(
      <SelectAmount moveToNextStep={moveToNextStep} planCode="XXXI" policyNumber="XXXI" />
    );

    const dateInput = getByLabelText('Effective date');
    fireEvent.change(dateInput, {
      target: { value: dayjs().add(1, 'day').format('MM/DD/YYYY') },
    });

    const continueButton = getByText('Continue');
    fireEvent.click(continueButton);

    expect(moveToNextStep).toHaveBeenCalled();
  });

  // Date before today shows dateOutOfRangeMessage
  it('should show dateOutOfRangeMessage when date is before today', async () => {
    const moveToNextStep = jest.fn();

    const { getByLabelText, getByText, findByText } = render(<SelectAmount moveToNextStep={moveToNextStep} planCode="XXXI" policyNumber="XXXI" />);

    const dateInput = getByLabelText('Effective date');
    fireEvent.change(dateInput, {
      target: { value: dayjs().subtract(1, 'day').format('MM/DD/YYYY') },
    });

    const continueButton = getByText('Continue');
    fireEvent.click(continueButton);

    const errorMessage = await findByText(dateOutOfRangeMessage);

    expect(errorMessage).toBeInTheDocument();
  });

  // Invalid date shows invalidDateMessage
  it('should show invalidDateMessage when date is not real', async () => {
    const moveToNextStep = jest.fn();
    const { getByLabelText, getByText, findByText } = render(<SelectAmount  moveToNextStep={moveToNextStep} planCode="XXXI" policyNumber="XXXI" />);

    const dateInput = getByLabelText('Effective date');
    fireEvent.change(dateInput, {
      target: { value: '24/32/202' },
    });

    const continueButton = getByText('Continue');
    fireEvent.click(continueButton);

    const errorMessage = await findByText(dateInvalidMessage);

    expect(errorMessage).toBeInTheDocument();
  });
});
