// Generated by CodiumAI
import { toSentenceCase, toTitleCase } from './strings';

describe('toTitleCase', () => {
  describe('a string with multiple words', () => {
    it("should return string with each word's first letter capitalized ", () => {
      const result = toTitleCase('this is a sentence');
      expect(result).toEqual('This Is A Sentence');
    });
  });

  it('should return an empty string when input is undefined', () => {
    const result = toTitleCase(undefined);
    expect(result).toEqual('');
  });

  it('should return an empty string when input is an empty string', () => {
    const result = toTitleCase('');
    expect(result).toEqual('');
  });
});

describe('toSentenceCase', () => {
  describe('a string with multiple words', () => {
    it('should return string with only the first letter capitalized ', () => {
      const result = toSentenceCase('this is a sentence');
      expect(result).toEqual('This is a sentence');
    });
  });

  it('should return an empty string when input is undefined', () => {
    const result = toSentenceCase(undefined);
    expect(result).toEqual('');
  });

  it('should return an empty string when input is an empty string', () => {
    const result = toSentenceCase('');
    expect(result).toEqual('');
  });
});
