export enum QueryKeys {
  NOTIFICATIONS = 'notifications',
  FEATURE_FLAGS = 'featureFlags',
  NOTIFICATION_ACKNOWLEDGMENT = 'notificationsAcknowledgment',
  PAYMENT_METHODS = 'paymentMethods',
  POLICY = 'policy',
  POLICY_PARTIES = 'policyParties',
  POLICY_PROFILE = 'policyProfile',
  POLICY_FUNDS = 'policyFunds',
  POLICY_STATUS = 'policyStatus',
  POLICY_ACKNOWLEDGMENT = 'policyAcknowledgment',
  USER_AUTHENTICATION_METHODS = 'userAuthenticationMethods',
  CASE_DETAILS = 'caseDetails',
  CASES_FOR_POLICY = 'casesForPolicy',
  CARRIER_CONFIG = 'carrierConfig',
  SYSTEMATIC_PREMIUMS = 'systematicPremiums',
  SYSTEMATIC_PREMIUMS_VALIDATION = 'systematicPremiumsValidation',
  COMPONENT_VISIBILITY = 'componentVisibility',
  FULL_SURRENDER_VALIDATION = 'fullSurrenderValidation',
}
