// Generated by CodiumAI

import { render, screen } from '@testing-library/react';

import MenuContextualLabel from './menu-contextual-label';

describe('MenuContextualLabel', () => {
    // Renders a span element with class 'flex flex-col gap-4'
    it("should render a span element with class 'flex flex-col gap-4' when children are passed", () => {
        render(
            <MenuContextualLabel label="Test Label">
                <div>Child 1</div>
                <div>Child 2</div>
            </MenuContextualLabel>
        );

        expect(screen.getByText('Test Label')).toBeInTheDocument();
        expect(screen.getByText('Child 1')).toBeInTheDocument();
        expect(screen.getByText('Child 2')).toBeInTheDocument();
    });
});
