// Generated by CodiumAI

import { render, screen } from '@testing-library/react';
import { ProgressStep } from './ProgressBarSteps';

describe('ProgressStep', () => {
  // renders step incomplete when isComplete is false

  describe('isComplete', () => {
    it('should render step incomplete when isComplete is false', () => {
      render(<ProgressStep number={1} isComplete={false} />);
      expect(
        screen.getByRole('presentation', { hidden: true })
      ).toBeInTheDocument();
      expect(screen.getByRole('presentation', { hidden: true })).toHaveClass(
        'stepIncomplete'
      );
    });

    it('should render step complete when isComplete is true', () => {
      const container = render(<ProgressStep number={1} isComplete={true} />);
      expect(
        screen.getByRole('presentation', { hidden: true })
      ).toBeInTheDocument();
      expect(screen.getByRole('presentation', { hidden: true })).toHaveClass(
        'step'
      );
      expect(
        container.container.querySelector('.typography-labels-field-label')
      ).not.toHaveTextContent('1');
    });
  });

  describe('current step', () => {
    // handles null value for isComplete
    it('should render step number when isComplete is null', () => {
      render(<ProgressStep number={1} isComplete={null} />);
      expect(
        screen.getByRole('presentation', { hidden: true })
      ).toBeInTheDocument();
      expect(screen.getByRole('presentation', { hidden: true })).toHaveClass(
        'step'
      );
      expect(screen.getByText('1')).toBeInTheDocument();
    });
  });
});
