export enum TitleCasedPartyRole {
    Agent = 'Agent',
    Assignee = 'Assignee',
    Beneficiary = 'Beneficiary',
    Insured = 'Insured',
    Owner = 'Owner',
    Payee = 'Payee',
    Payor = 'Payor',
    Primary = 'Primary',
    RiderInsured = 'Rider Insured',
    SecondaryAssignee = 'Secondary assignee',
    ThirdPartyDesignee = 'Third Party Designee',
    JointOwner = 'Joint Owner',
}

export const partyRoleOrder: TitleCasedPartyRole[] = [
    TitleCasedPartyRole.Owner,
    TitleCasedPartyRole.Insured,
    TitleCasedPartyRole.Payor,
    TitleCasedPartyRole.Beneficiary,
    TitleCasedPartyRole.Agent,
    TitleCasedPartyRole.Payee,
    TitleCasedPartyRole.Assignee,
    TitleCasedPartyRole.RiderInsured,
];

export enum PartyRoleChipToText {
    AdditionalWritingAgent = 'additionalwritingagent',
    Agent = 'agent',
    AgentOfRecord = 'agent,agent of record',
    Annuitant = 'annuitant',
    JointAnnuitant = 'jointannuitant',
    Assignee = 'assignee',
    Beneficiary = 'beneficiary',
    CommissionAgent = 'commissionagent',
    ContingentBeneficiary = 'contingentbeneficiary',
    ExchangeCompany = 'exchangecompany',
    Insured = 'insured',
    JointOwner = 'owner,joint',
    JointOwnerDifferentAddress = 'owner,joint, different address',
    JointOwnerSameAddress = 'owner,joint, same address',
    Owner = 'owner',
    OwnerDeceased = 'owner deceased,primary',
    Payee = 'payee',
    Payor = 'payor',
    PolicyJointOwner = 'jointowner',
    PrimaryBeneficiary = 'primarybeneficiary',
    PrimaryOwner = 'owner,primary',
    PrimaryServicingAgent = 'primaryservicingagent',
    PrimaryWritingAgent = 'primarywritingagent',
    RiderInsured = 'coverageinsured',
    SellingAgent = 'sellingagent',
    ServicingAgent = 'servicingagent',
    ThirdPartyDesignee = 'thirdpartydesignee',
    OtherIntresedParty = 'otherinterestedparty',
    AdditionalServicingAgent = 'additionalservicingagent',
}
