export const widgetRegistryMock = {
    fields: {},
    widgets: {},
    templates: {
        ArrayFieldTemplate: () => null,
        ArrayFieldDescriptionTemplate: () => null,
        ArrayFieldItemTemplate: () => null,
        ArrayFieldTitleTemplate: () => null,
        ButtonTemplates: {
            SubmitButton: () => null,
            AddButton: () => null,
            CopyButton: () => null,
            MoveDownButton: () => null,
            MoveUpButton: () => null,
            RemoveButton: () => null,
        },
        DescriptionFieldTemplate: () => null,
        ErrorListTemplate: () => null,
        FieldTemplate: () => null,
        ObjectFieldTemplate: () => null,
        TitleFieldTemplate: () => null,
        WrapIfAdditionalTemplate: () => null,
        UnsupportedFieldTemplate: () => null,
        BaseInputTemplate: () => null,
        FieldErrorTemplate: () => null,
        FieldHelpTemplate: () => null,
    },
    formContext: {},
    rootSchema: {},
    schemaUtils: {
        getDisplayLabel: () => false,
        getMatchingOption: () => 0,
        getFirstMatchingOption: () => 0,
        retrieveSchema: () => ({}),
        toIdSchema: () => ({ $id: '' }),
        isMultiSelect: () => false,
        isFilesArray: () => false,
        getDefaultFormState: () => ({}),
        getValidator: () => ({
            validateFormData: jest.fn(),
            toErrorList: jest.fn(),
            isValid: jest.fn(),
            rawValidation: jest.fn(),
        }),
        doesSchemaUtilsDiffer: () => false,
        getClosestMatchingOption: () => 0,
        isSelect: () => false,
        mergeValidationData: jest.fn(),
        sanitizeDataForNewSchema: jest.fn(),
        toPathSchema: jest.fn(),
    },
    translateString: (id: string) => id,
};
