// Generated by CodiumAI

import { render, screen } from '@testing-library/react';

import { BadgeVariant } from '@deps/components/badge/badge.helper';
import { PolicyStatus, ProductType } from '@deps/models/policy/sor-policy';
import { getCarrierNameByClientId } from '@deps/utils/carriers';
import SideSheetProductDetails from './side-sheet-product-details';

jest.mock('@deps/helpers/translation.helper', () => ({
    mapProductTypeToTranslation: (productType: string) => ({
        label: productType,
    }),
}));
jest.mock('@deps/utils/server-logging');

describe('SideSheetProductDetails', () => {
    // Renders all labels and values correctly with default props
    it('should render all labels and values correctly with default props', async () => {
        // Arrange
        const globalValues = {
            carrierId: 'SBUL',
            glPlanCode: '123',
            marketingName: 'Product A',
            planCode: '456',
            planName: 'Plan A',
            policyNumber: 'AU123456789',
            productType: 'UNIVERSALLIFE' as ProductType,
            status: 'Active' as PolicyStatus,
            tooltip: 'Test tooltip',
            variant: 'Default' as BadgeVariant,
        };

        // Act
        render(<SideSheetProductDetails globalValues={globalValues} />);

        // Assert
        expect(await screen.findByText('dashboard.productDetails')).toBeInTheDocument();

        expect(await screen.findByText('globalPolicyInfo.carrierName')).toBeInTheDocument();
        expect(await screen.findByText(getCarrierNameByClientId('SBUL'))).toBeInTheDocument();

        expect(await screen.findByText('globalPolicyInfo.productMarketingName')).toBeInTheDocument();
        expect(await screen.findByText('Product A')).toBeInTheDocument();

        expect(await screen.findByText('globalPolicyInfo.productName')).toBeInTheDocument();
        expect(await screen.findByText('Plan A')).toBeInTheDocument();

        expect(await screen.findByText('globalPolicyInfo.productType')).toBeInTheDocument();
        expect(await screen.findByText('UNIVERSALLIFE')).toBeInTheDocument();

        expect(await screen.findByText('globalPolicyInfo.productCode')).toBeInTheDocument();
        expect(await screen.findByText('123')).toBeInTheDocument();

        expect(await screen.findByText('globalPolicyInfo.planCode')).toBeInTheDocument();
        expect(await screen.findByText('456')).toBeInTheDocument();
    });
});
