// Generated by CodiumAI
import '@testing-library/jest-dom';

import { render, screen } from '@testing-library/react';

import { ChildCard, ClickableCardContainer } from './ClickableCardContainer';

describe('ClickableCardContainer', () => {
  // Renders the component with children and a link arrow if linkTo prop is provided and disabled prop is false
  it('should render the component with children and a link arrow when linkTo prop is provided and disabled prop is false', () => {
    // Arrange
    const children = <div>Children</div>;
    const linkTo = {
      url: 'https://example.com',
      label: 'Link',
      isInternal: false,
    };
    const disabled = false;

    // Act
    render(
      <ClickableCardContainer linkTo={linkTo} disabled={disabled}>
        {children}
      </ClickableCardContainer>
    );

    // Assert
    expect(screen.getByText('Children')).toBeInTheDocument();
    expect(screen.getByLabelText('Link')).toBeInTheDocument();
  });

  // Renders the component with children and without a link arrow if linkTo prop is not provided
  it('should render the component with children and without a link arrow when linkTo prop is not provided', () => {
    // Arrange
    const children = <div>Children</div>;

    // Act
    render(<ClickableCardContainer>{children}</ClickableCardContainer>);

    // Assert
    expect(screen.getByText('Children')).toBeInTheDocument();
    expect(screen.queryByLabelText('Link')).not.toBeInTheDocument();
  });

  // Renders the component with children and without a link arrow if linkTo prop is provided but disabled prop is true
  it('should render the component with children and without a link arrow when linkTo prop is provided but disabled prop is true', () => {
    // Arrange
    const children = <div>Children</div>;
    const linkTo = {
      url: 'https://example.com',
      label: 'Link',
      isInternal: false,
    };
    const disabled = true;

    // Act
    render(
      <ClickableCardContainer linkTo={linkTo} disabled={disabled}>
        {children}
      </ClickableCardContainer>
    );

    // Assert
    expect(screen.getByText('Children')).toBeInTheDocument();
    expect(screen.queryByLabelText('Link')).not.toBeInTheDocument();
  });

  // Renders the component with children and without a link arrow if linkTo prop is provided but url is empty
  it('should render the component with children and without a link arrow when linkTo prop is provided but url is empty', () => {
    // Arrange
    const children = <div>Children</div>;
    const linkTo = { url: '', label: 'Link', isInternal: false };

    // Act
    render(
      <ClickableCardContainer linkTo={linkTo}>
        {children}
      </ClickableCardContainer>
    );

    // Assert
    expect(screen.getByText('Children')).toBeInTheDocument();
    expect(screen.queryByLabelText('Link')).not.toBeInTheDocument();
  });

  // Renders the next link component when an internal link is passed
  it('should render the component with a next link component when an internal route is passed', () => {
    // Arrange
    const children = <div>Children</div>;
    const linkTo = { url: '', label: 'Link', isInternal: true };

    // Act
    render(
      <ClickableCardContainer linkTo={linkTo}>
        {children}
      </ClickableCardContainer>
    );

    // Assert
    expect(screen.getByText('Children')).toBeInTheDocument();
    expect(screen.queryByRole('a')).not.toBeInTheDocument();
  });

  // Renders the component with children and without a list of child cards if listItems prop is provided but empty
  it('should render the component with children and without a list of child cards when listItems prop is provided but empty', () => {
    // Arrange
    const children = <div>Children</div>;
    const listItems = [] as ChildCard[];

    // Act
    render(
      <ClickableCardContainer listItems={listItems}>
        {children}
      </ClickableCardContainer>
    );

    // Assert
    expect(screen.getByText('Children')).toBeInTheDocument();
    expect(screen.queryByRole('list')).not.toBeInTheDocument();
  });

  // Renders the component with children and without a list of child cards if listItems prop is not provided
  it('should render the component with children and without a list of child cards when listItems prop is not provided', () => {
    // Arrange
    const children = <div>Children</div>;

    // Act
    render(<ClickableCardContainer>{children}</ClickableCardContainer>);

    // Assert
    expect(screen.getByText('Children')).toBeInTheDocument();
    expect(screen.queryByRole('list')).not.toBeInTheDocument();
  });
});
