export const illustrationsMockData = [
    {
        id: 'case-001',
        title: 'Life Policy for John',
        caseManagementCaseId: 'cmc-001',
        eAppId: 'eapp-101',
        agentDetails: {
            agencyId: 'agency-789',
            npn: '1234567',
            firstName: 'Emily',
            lastName: 'Clark',
        },
        insuredDetails: {
            firstName: 'John',
            lastName: 'Doe',
            sexAtBirth: 'Male',
            dateOfBirth: '1980-05-12',
            nicotineUser: false,
            state: 'CA',
            illustrateAtOlderAge: false,
            issueAge: 44,
            riskClass: 'PreferredPlus',
        },
        lastModified: '2025-06-10T14:32:00Z',
    },
    {
        id: 'case-002',
        title: 'Policy for Jane Smith',
        caseManagementCaseId: 'cmc-002',
        eAppId: 'eapp-102',
        agentDetails: {
            agencyId: 'agency-456',
            npn: '9876543',
            firstName: 'David',
            lastName: 'Nguyen',
        },
        insuredDetails: {
            firstName: 'Jane',
            lastName: 'Smith',
            sexAtBirth: 'Female',
            dateOfBirth: '1992-11-03',
            nicotineUser: true,
            state: 'TX',
            illustrateAtOlderAge: true,
            issueAge: 32,
            riskClass: 'Standard',
        },
        lastModified: '2025-06-11T09:15:00Z',
    },
    {
        id: 'case-003',
        title: 'Retirement Life Coverage for Mark',
        caseManagementCaseId: 'cmc-003',
        eAppId: 'eapp-103',
        agentDetails: {
            agencyId: 'agency-321',
            npn: '1122334',
            firstName: 'Sarah',
            lastName: 'Johnson',
        },
        insuredDetails: {
            firstName: 'Mark',
            lastName: 'Taylor',
            sexAtBirth: 'Male',
            dateOfBirth: '1975-09-27',
            nicotineUser: false,
            state: 'FL',
            illustrateAtOlderAge: false,
            issueAge: 49,
            riskClass: 'Preferred',
        },
        lastModified: '2025-06-12T17:48:00Z',
    },
];
