// Generated by CodiumAI

import { render } from '@testing-library/react';

import { StatusIconText } from './StatusIconText';

describe('StatusIconText', () => {
  // renders 'Eligible' text when isEligible is true
  it('should render "Eligible" text when isEligible is true', () => {
    const { getByText } = render(
      <StatusIconText isEligible={true} showIcon={false} />
    );
    expect(getByText('Eligible')).toBeInTheDocument();
  });

  // returns null when isEligible is null
  it('should return null when isEligible is null', () => {
    const { container } = render(
      <StatusIconText isEligible={null} showIcon={false} />
    );
    expect(container.firstChild).toBeNull();
  });
});
