export enum ComponentName {
  OWNER_PROFILE = 'OWNER_PROFILE',
  PAYOR_PROFILE = 'PAYOR_PROFILE',
  OVERVIEW_PREMIUM_LINK = 'OVERVIEW_PREMIUM_LINK',
  OVERVIEW_PREMIUM_DETAILED_VIEW = 'OVERVIEW_PREMIUM_DETAILED_VIEW',
  OVERVIEW_PAYMENT_HISTORY = 'OVERVIEW_PAYMENT_HISTORY',
  OVERVIEW_COVERAGE = 'OVERVIEW_COVERAGE',
  OVERVIEW_ACCOUNT_VALUE = 'OVERVIEW_ACCOUNT_VALUE',
  OVERVIEW_BENEFICIARIES = 'OVERVIEW_BENEFICIARIES',
  OVERVIEW_RIDERS = 'OVERVIEW_RIDERS',
  OVERVIEW_DOCUMENTS = 'OVERVIEW_DOCUMENTS',
}
