import type { FieldDefinition, FieldRegistry } from './types';

/**
 * Central field registry — the single source of truth for all field definitions.
 *
 * To rename a field label across all transactions:
 *   1. Update `label` here
 *   2. Re-compose schemas (or they recompile at request time automatically)
 *
 * To add a new field: add an entry here and reference it by ID in any TransactionDefinition.
 */
export const DEFAULT_FIELD_REGISTRY: FieldRegistry = {
    // ── Personal Information ──────────────────────────────────────────────────
    firstName: {
        id: 'firstName',
        label: 'First Name',
        type: 'string',
        group: 'Personal Information',
        tags: ['person', 'name'],
        validation: { minLength: 1, maxLength: 50 },
        personas: { selfServe: { required: true } },
    },
    middleName: {
        id: 'middleName',
        label: 'Middle Name',
        type: 'string',
        group: 'Personal Information',
        tags: ['person', 'name'],
        validation: { maxLength: 50 },
    },
    lastName: {
        id: 'lastName',
        label: 'Last Name',
        type: 'string',
        group: 'Personal Information',
        tags: ['person', 'name'],
        validation: { minLength: 1, maxLength: 50 },
        personas: { selfServe: { required: true } },
    },
    dateOfBirth: {
        id: 'dateOfBirth',
        label: 'Date of Birth',
        type: 'date',
        group: 'Personal Information',
        tags: ['person', 'date'],
        widget: 'DateWidget',
        personas: { selfServe: { required: true } },
    },
    gender: {
        id: 'gender',
        label: 'Gender',
        type: 'select',
        group: 'Personal Information',
        tags: ['person'],
        validation: {
            enum: ['M', 'F', 'X'],
            enumNames: ['Male', 'Female', 'Non-binary'],
        },
    },
    prefix: {
        id: 'prefix',
        label: 'Prefix',
        type: 'select',
        group: 'Personal Information',
        tags: ['person', 'name'],
        validation: {
            enum: ['Mr.', 'Mrs.', 'Ms.', 'Dr.', 'Rev.'],
            enumNames: ['Mr.', 'Mrs.', 'Ms.', 'Dr.', 'Rev.'],
        },
    },
    suffix: {
        id: 'suffix',
        label: 'Suffix',
        type: 'select',
        group: 'Personal Information',
        tags: ['person', 'name'],
        validation: {
            enum: ['Jr.', 'Sr.', 'II', 'III', 'IV', 'V'],
            enumNames: ['Jr.', 'Sr.', 'II', 'III', 'IV', 'V'],
        },
    },
    trustName: {
        id: 'trustName',
        label: 'Trust Name',
        type: 'string',
        group: 'Personal Information',
        tags: ['trust'],
        validation: { minLength: 1, maxLength: 100 },
    },

    // ── Identification ────────────────────────────────────────────────────────
    ssn: {
        id: 'ssn',
        label: 'Social Security Number',
        type: 'ssn',
        group: 'Identification',
        tags: ['identity', 'sensitive'],
        validation: { pattern: '^\\d{3}-?\\d{2}-?\\d{4}$' },
        uiOptions: { mask: true },
    },
    taxId: {
        id: 'taxId',
        label: 'Tax ID (EIN)',
        type: 'string',
        group: 'Identification',
        tags: ['identity', 'business'],
        validation: { pattern: '^\\d{2}-?\\d{7}$' },
    },
    driversLicense: {
        id: 'driversLicense',
        label: "Driver's License Number",
        type: 'string',
        group: 'Identification',
        tags: ['identity'],
        validation: { maxLength: 20 },
    },

    // ── Contact ───────────────────────────────────────────────────────────────
    email: {
        id: 'email',
        label: 'Email Address',
        type: 'email',
        group: 'Contact',
        tags: ['contact'],
        validation: { pattern: '^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$' },
    },
    phone: {
        id: 'phone',
        label: 'Phone Number',
        type: 'phone',
        group: 'Contact',
        tags: ['contact'],
        validation: { pattern: '^[\\d\\s\\-().+]+$', minLength: 10 },
    },
    phoneType: {
        id: 'phoneType',
        label: 'Phone Type',
        type: 'select',
        group: 'Contact',
        tags: ['contact'],
        validation: {
            enum: ['HOME', 'WORK', 'MOBILE', 'FAX'],
            enumNames: ['Home', 'Work', 'Mobile', 'Fax'],
        },
    },

    // ── Address ───────────────────────────────────────────────────────────────
    addressLine1: {
        id: 'addressLine1',
        label: 'Street Address',
        type: 'string',
        group: 'Address',
        tags: ['address'],
        validation: { minLength: 5, maxLength: 100 },
        personas: { selfServe: { required: true } },
    },
    addressLine2: {
        id: 'addressLine2',
        label: 'Apt / Suite / Unit',
        type: 'string',
        group: 'Address',
        tags: ['address'],
        validation: { maxLength: 50 },
    },
    city: {
        id: 'city',
        label: 'City',
        type: 'string',
        group: 'Address',
        tags: ['address'],
        validation: { minLength: 2, maxLength: 50 },
        personas: { selfServe: { required: true } },
    },
    state: {
        id: 'state',
        label: 'State',
        type: 'select',
        group: 'Address',
        tags: ['address'],
        validation: {
            enum: [
                'AL',
                'AK',
                'AZ',
                'AR',
                'CA',
                'CO',
                'CT',
                'DE',
                'FL',
                'GA',
                'HI',
                'ID',
                'IL',
                'IN',
                'IA',
                'KS',
                'KY',
                'LA',
                'ME',
                'MD',
                'MA',
                'MI',
                'MN',
                'MS',
                'MO',
                'MT',
                'NE',
                'NV',
                'NH',
                'NJ',
                'NM',
                'NY',
                'NC',
                'ND',
                'OH',
                'OK',
                'OR',
                'PA',
                'RI',
                'SC',
                'SD',
                'TN',
                'TX',
                'UT',
                'VT',
                'VA',
                'WA',
                'WV',
                'WI',
                'WY',
            ],
            enumNames: [
                'Alabama',
                'Alaska',
                'Arizona',
                'Arkansas',
                'California',
                'Colorado',
                'Connecticut',
                'Delaware',
                'Florida',
                'Georgia',
                'Hawaii',
                'Idaho',
                'Illinois',
                'Indiana',
                'Iowa',
                'Kansas',
                'Kentucky',
                'Louisiana',
                'Maine',
                'Maryland',
                'Massachusetts',
                'Michigan',
                'Minnesota',
                'Mississippi',
                'Missouri',
                'Montana',
                'Nebraska',
                'Nevada',
                'New Hampshire',
                'New Jersey',
                'New Mexico',
                'New York',
                'North Carolina',
                'North Dakota',
                'Ohio',
                'Oklahoma',
                'Oregon',
                'Pennsylvania',
                'Rhode Island',
                'South Carolina',
                'South Dakota',
                'Tennessee',
                'Texas',
                'Utah',
                'Vermont',
                'Virginia',
                'Washington',
                'West Virginia',
                'Wisconsin',
                'Wyoming',
            ],
        },
        personas: { selfServe: { required: true } },
    },
    zipCode: {
        id: 'zipCode',
        label: 'ZIP Code',
        type: 'string',
        group: 'Address',
        tags: ['address'],
        validation: { pattern: '^\\d{5}(-\\d{4})?$' },
        personas: { selfServe: { required: true } },
    },
    country: {
        id: 'country',
        label: 'Country',
        type: 'select',
        group: 'Address',
        tags: ['address'],
        validation: {
            enum: ['US', 'CA', 'MX'],
            enumNames: ['United States', 'Canada', 'Mexico'],
        },
    },

    // ── Party / Role ──────────────────────────────────────────────────────────
    partyRole: {
        id: 'partyRole',
        label: 'Party Role',
        type: 'select',
        group: 'Party',
        tags: ['party', 'role'],
        validation: {
            enum: [
                'OWNER',
                'JOINTOWNER',
                'PRIMARYBENEFICIARY',
                'CONTINGENTBENEFICIARY',
                'PAYEE',
                'ASSIGNEE',
                'ANNUITANT',
                'INSURED',
            ],
            enumNames: [
                'Owner',
                'Joint Owner',
                'Primary Beneficiary',
                'Contingent Beneficiary',
                'Payee',
                'Assignee',
                'Annuitant',
                'Insured',
            ],
        },
        widget: 'PartyRoleWidget',
    },
    partyType: {
        id: 'partyType',
        label: 'Party Type',
        type: 'select',
        group: 'Party',
        tags: ['party'],
        validation: {
            enum: ['PERSON', 'ORGANIZATION', 'TRUST'],
            enumNames: ['Person', 'Organization', 'Trust'],
        },
    },
    relationship: {
        id: 'relationship',
        label: 'Relationship to Owner',
        type: 'select',
        group: 'Party',
        tags: ['party', 'relationship'],
        validation: {
            enum: [
                'SPOUSE',
                'CHILD',
                'PARENT',
                'SIBLING',
                'GRANDCHILD',
                'GRANDPARENT',
                'DOMESTIC_PARTNER',
                'OTHER',
            ],
            enumNames: [
                'Spouse',
                'Child',
                'Parent',
                'Sibling',
                'Grandchild',
                'Grandparent',
                'Domestic Partner',
                'Other',
            ],
        },
    },
    allocationPercentage: {
        id: 'allocationPercentage',
        label: 'Allocation %',
        type: 'number',
        group: 'Party',
        tags: ['allocation'],
        widget: 'AllocationPercentageWidget',
        validation: { minimum: 0, maximum: 100 },
    },

    // ── Banking ───────────────────────────────────────────────────────────────
    bankName: {
        id: 'bankName',
        label: 'Bank Name',
        type: 'string',
        group: 'Banking',
        tags: ['bank', 'financial'],
        validation: { minLength: 2, maxLength: 100 },
    },
    bankAccountNumber: {
        id: 'bankAccountNumber',
        label: 'Account Number',
        type: 'string',
        group: 'Banking',
        tags: ['bank', 'sensitive'],
        uiOptions: { mask: true },
        validation: { minLength: 4, maxLength: 20 },
    },
    bankRoutingNumber: {
        id: 'bankRoutingNumber',
        label: 'Routing Number',
        type: 'string',
        group: 'Banking',
        tags: ['bank'],
        validation: { pattern: '^\\d{9}$' },
    },
    bankAccountType: {
        id: 'bankAccountType',
        label: 'Account Type',
        type: 'select',
        group: 'Banking',
        tags: ['bank'],
        validation: {
            enum: ['CHECKING', 'SAVINGS'],
            enumNames: ['Checking', 'Savings'],
        },
    },

    // ── Policy ────────────────────────────────────────────────────────────────
    policyNumber: {
        id: 'policyNumber',
        label: 'Policy Number',
        type: 'string',
        group: 'Policy',
        tags: ['policy'],
        validation: { minLength: 5, maxLength: 30 },
        personas: { paper: { readOnly: true }, selfServe: { readOnly: true } },
    },
    effectiveDate: {
        id: 'effectiveDate',
        label: 'Effective Date',
        type: 'date',
        group: 'Policy',
        tags: ['policy', 'date'],
        widget: 'DateWidget',
    },
    witnessName: {
        id: 'witnessName',
        label: 'Witness Name',
        type: 'string',
        group: 'Policy',
        tags: ['policy', 'signature'],
        validation: { minLength: 1, maxLength: 100 },
        personas: { selfServe: { hidden: true } },
    },

    // ── Notes / Comments ──────────────────────────────────────────────────────
    notes: {
        id: 'notes',
        label: 'Notes',
        type: 'textarea',
        group: 'Notes',
        tags: ['notes'],
        widget: 'NotesWidget',
        validation: { maxLength: 2000 },
    },
    agentNotes: {
        id: 'agentNotes',
        label: 'Agent Notes',
        type: 'textarea',
        group: 'Notes',
        tags: ['notes', 'agent'],
        widget: 'ProcessorNotesWidget',
        personas: {
            selfServe: { hidden: true },
        },
        validation: { maxLength: 2000 },
    },
    reason: {
        id: 'reason',
        label: 'Reason for Change',
        type: 'textarea',
        group: 'Notes',
        tags: ['notes'],
        validation: { maxLength: 500 },
    },

    // ── Signature ─────────────────────────────────────────────────────────────
    signature: {
        id: 'signature',
        label: 'Signature',
        type: 'string',
        group: 'Signature',
        tags: ['signature'],
        personas: { selfServe: { required: true } },
    },
    signatureDate: {
        id: 'signatureDate',
        label: 'Signature Date',
        type: 'date',
        group: 'Signature',
        tags: ['signature', 'date'],
        widget: 'DateWidget',
    },
    attestation: {
        id: 'attestation',
        label: 'I certify the information above is accurate',
        type: 'boolean',
        group: 'Signature',
        tags: ['signature'],
        widget: 'CheckboxWidget',
        personas: { selfServe: { required: true } },
    },
};

/** Return all unique groups in registration order */
export function getFieldGroups(registry: FieldRegistry): string[] {
    const seen = new Set<string>();
    const groups: string[] = [];
    for (const field of Object.values(registry)) {
        if (!seen.has(field.group)) {
            seen.add(field.group);
            groups.push(field.group);
        }
    }
    return groups;
}

/** Return fields belonging to a group */
export function getFieldsByGroup(
    registry: FieldRegistry,
    group: string
): FieldDefinition[] {
    return Object.values(registry).filter((f) => f.group === group);
}
