// Generated by CodiumAI
import '@testing-library/jest-dom';

import { render, screen } from '@testing-library/react';

import { FieldData } from './FieldData';

describe('FieldData', () => {
  // Renders the component with the provided fieldData and caption
  it('should render the component with the provided fieldData and caption', () => {
    // Arrange
    const fieldData = 'Test Field Data';
    const caption = 'Test Caption';

    // Act
    render(<FieldData fieldData={fieldData} caption={caption} />);

    // Assert
    expect(screen.getByText(fieldData)).toBeInTheDocument();
    expect(screen.getByText(caption)).toBeInTheDocument();
  });

  // Should not render the component with empty fieldData
  it('should not render the component with empty fieldData', () => {
    // Arrange
    const fieldData = '';
    const caption = 'caption';

    // Act
    render(<FieldData fieldData={fieldData} caption={caption} />);

    // Assert
    expect(screen.queryByText(caption)).not.toBeInTheDocument();
  });
});
