// Generated by CodiumAI

import { handleKeyPressDateCharactersOnly } from './utils';

describe('handleKeyPress', () => {
  // Allows numeric key presses
  it('should allow numeric key presses', () => {
    const event = new KeyboardEvent('keypress', { key: '1' });
    const preventDefault = jest.fn();
    event.preventDefault = preventDefault;

    handleKeyPressDateCharactersOnly(event);

    expect(preventDefault).not.toHaveBeenCalled();
  });

  // Handles empty key press
  it('should prevent default action for empty key press', () => {
    const event = new KeyboardEvent('keypress', { key: '' });
    const preventDefault = jest.fn();
    event.preventDefault = preventDefault;

    handleKeyPressDateCharactersOnly(event);

    expect(preventDefault).toHaveBeenCalled();
  });
});
