// Generated by CodiumAI

import { render } from '@testing-library/react';
import { Label } from '@zinnia/bloom/components';

import { FieldDate } from './FieldDate';

describe('FieldDate', () => {
  // Renders input with initial selected date
  it('should render input with initial selected date', () => {
    const today = new Date();
    const { getByPlaceholderText } = render(
      <FieldDate
        selectedDate={new Date()}
        onDateSelect={() => {}}
        label={<Label>label</Label>}
        name="test-date"
        placeholder="Please select a date"
      />
    );
    const input = getByPlaceholderText('Please select a date');

    expect(input).toHaveValue(today.toLocaleDateString());
  });

  // Handles empty input value gracefully
  it('should handle empty input value gracefully', () => {
    const { getByPlaceholderText } = render(
      <FieldDate
        selectedDate={undefined}
        onDateSelect={() => {}}
        label={<Label>label</Label>}
        name="test-date"
        placeholder="Please select a date"
      />
    );
    const input = getByPlaceholderText('Please select a date');
    expect(input).toHaveValue('');
  });
});
