const { fixupConfigRules, fixupPluginRules } = require('@eslint/compat');
const { FlatCompat } = require('@eslint/eslintrc');
const js = require('@eslint/js');
const typescriptEslint = require('@typescript-eslint/eslint-plugin');
const tsParser = require('@typescript-eslint/parser');
const checkFile = require('eslint-plugin-check-file');
const _import = require('eslint-plugin-import');
const onlyWarn = require('eslint-plugin-only-warn');
const reactHooks = require('eslint-plugin-react-hooks');
const reactRefresh = require('eslint-plugin-react-refresh');
const { resolve } = require('node:path');

const globals = require('globals');

const compat = new FlatCompat({
    baseDirectory: __dirname,
    recommendedConfig: js.configs.recommended,
    allConfig: js.configs.all,
});

const project = resolve(process.cwd(), 'tsconfig.json');

const baseExtends = compat
    .config({
        extends: [
            'eslint:recommended',
            'plugin:react/recommended',
            'plugin:react-hooks/recommended',
            'plugin:import/recommended',
            'plugin:storybook/recommended',
            'prettier',
            'plugin:@typescript-eslint/recommended',
            'turbo',
            'plugin:@next/next/recommended',
            'plugin:@tanstack/eslint-plugin-query/recommended',
            'plugin:@vitest/legacy-recommended',
        ],
    })
    .flatMap((config) => fixupConfigRules(config));

module.exports = [
    ...baseExtends,
    {
        languageOptions: {
            globals: {
                ...globals.node,
                ...globals.browser,
                React: true,
                JSX: true,
            },

            parser: tsParser,
            ecmaVersion: 'latest',
            sourceType: 'module',
            parserOptions: {},
        },

        plugins: {
            'only-warn': onlyWarn,
            '@typescript-eslint': fixupPluginRules(typescriptEslint),
            'check-file': checkFile,
            import: fixupPluginRules(_import),
            'react-refresh': reactRefresh,
            'react-hooks': fixupPluginRules(reactHooks),
        },

        settings: {
            react: {
                version: 'detect',
            },

            'import/resolver': {
                typescript: {
                    project,
                },

                alias: {
                    map: [['@/', './src']],
                },
            },
        },

        rules: {
            'turbo/no-undeclared-env-vars': 'off',
            'react/prop-types': 'off',
            'no-unused-vars': 'off',

            '@typescript-eslint/no-unused-vars': [
                'error',
                {
                    argsIgnorePattern: '^_',
                    caughtErrors: 'none',
                    ignoreRestSiblings: true,
                    varsIgnorePattern: '^_',
                    vars: 'all',
                },
            ],

            'check-file/filename-blocklist': [
                'error',
                {
                    '**/*.model.ts': '*.models.ts',
                    '**/*.util.ts': '*.utils.ts',
                    '**/*.helper.ts': '*.helpers.ts',
                },
            ],

            '@typescript-eslint/no-explicit-any': 'off',
            'react-hooks/exhaustive-deps': 'warn',
            'react/no-unescaped-entities': 'off',
            'no-control-regex': 'off',
            'react/no-unstable-nested-components': 'error',

            'import/order': [
                'error',
                {
                    groups: [
                        ['builtin', 'external'],
                        'internal',
                        ['parent', 'sibling', 'index'],
                        ['type', 'unknown'],
                    ],

                    pathGroups: [
                        {
                            pattern: '@deps/**',
                            group: 'internal',
                        },
                        {
                            pattern: 'next-i18next.config',
                            group: 'internal',
                        },
                    ],

                    pathGroupsExcludedImportTypes: [],
                    'newlines-between': 'always',

                    alphabetize: {
                        order: 'asc',
                        caseInsensitive: true,
                    },
                },
            ],

            'import/no-unresolved': [
                'error',
                {
                    ignore: ['^https?://'],
                },
            ],
        },
    },
    {
        ignores: [
            '**/.*.js',
            '**/node_modules',
            '**/dist',
            '**/next-env.d.ts',
            '**/postcss.config.js',
            '**/config-overrides.js',
            '**/.next/**',
            '**/.storybook/**',
            '**/storybook-static/**',
            '**/e2e/**',
            '**/api-types/**',
            '**/scripts/**',
        ],
    },
    {
        files: [
            '**/*.config.js',
            '**/*.config.cjs',
            '**/*.config.mjs',
            '**/*.config.ts',
            'next.config.js',
            'next-i18next.config.js',
        ],

        rules: {
            '@typescript-eslint/no-var-requires': 'off',
        },
    },
    {
        files: ['**/*.js?(x)', '**/*.ts?(x)'],

        rules: {
            'storybook/hierarchy-separator': 'off',
            'storybook/default-exports': 'off',
            'storybook/story-exports': 'off',
        },
    },
    {
        files: ['src/**/*.stories.@(ts|tsx|js|jsx|mjs|cjs)'],

        rules: {
            'storybook/hierarchy-separator': 'error',
            'storybook/default-exports': 'error',
            'storybook/story-exports': 'error',
        },
    },
    {
        files: ['**/*.stories.tsx'],

        rules: {
            '@next/next/no-html-link-for-pages': 'off',
        },
    },
    {
        files: [
            'src/components/button-group/button-group.stories.tsx',
            'src/components/card/card-upcoming-payment/pending-upcoming-banner/pending-upcoming-banner.tsx',
            'src/components/case-document-select/case-document-select.tsx',
            'src/components/case-sub-page/case-tabs/call-audio-player.tsx',
            'src/components/ceding-company-signature/ceding-company-signature.tsx',
            'src/components/checkbox/checkbox.tsx',
            'src/components/dashboard/charts/bar-charts/stacked-column-chart.tsx',
            'src/components/dynamic-form/customization/components/document-metadata/metadata-filter.tsx',
            'src/components/dynamic-form/customization/templates/array-field-template/TransactionsArrayFieldTemplate.tsx',
            'src/components/dynamic-form/customization/templates/change-address-templete/change-address-template.tsx',
            'src/components/dynamic-form/customization/widgets/agent-summary-widget/agent-summary-widget.tsx',
            'src/components/dynamic-form/customization/widgets/allocation-percentage/allocation-percentage.tsx',
            'src/components/dynamic-form/customization/widgets/arithmetic-operation-widget/arithmetic-operation-widget.tsx',
            'src/components/dynamic-form/customization/widgets/checkboxes-select-widget/checkboxes-select-widget.tsx',
            'src/components/dynamic-form/customization/widgets/checkboxes-widget/checkboxes-widget.tsx',
            'src/components/dynamic-form/customization/widgets/file-widget/file-widget.tsx',
            'src/components/dynamic-form/customization/widgets/radio-widget/radio-widget.tsx',
            'src/components/illustrations/helpers/hooks/use-select-illustration-for-application.tsx',
            'src/components/otp-renewal-form/call-receive-date.tsx',
            'src/components/otp-renewal-form/owner-information/owner-information-helpers.tsx',
            'src/components/otp-renewal-form/owner-information/owner-information.tsx',
            'src/components/otp-renewal-form/renewal-period-multi-selection.tsx',
            'src/components/otp-renewal-form/renewal-period-single-selection.tsx',
            'src/components/otp-renewal-form/signature-validation/single-signature.tsx',
            'src/components/otp-send-document/components/additional-recipient.tsx',
            'src/components/otp-send-document/components/tax-forms-listing.tsx',
            'src/components/otp-send-document/statement-selection.tsx',
            'src/components/otp-send-document/tax-forms-selection.tsx',
            'src/components/otp-withdrawal-form/address-details.tsx',
            'src/components/otp-withdrawal-form/address-entry.tsx',
            'src/components/otp-withdrawal-form/amount-details.tsx',
            'src/components/otp-withdrawal-form/beneficiary-information/beneficiary-info.tsx',
            'src/components/otp-withdrawal-form/csln-check.tsx',
            'src/components/otp-withdrawal-form/distribution-instructions/fund-allocations.tsx',
            'src/components/otp-withdrawal-form/employer-tpa-authorization.tsx',
            'src/components/otp-withdrawal-form/financial-professional-signature.tsx',
            'src/components/otp-withdrawal-form/form-disbursement/form-disbursement-parts/autofill-account-toggle.tsx',
            'src/components/otp-withdrawal-form/form-disbursement/form-disbursement-parts/consent-available.tsx',
            'src/components/otp-withdrawal-form/form-disbursement/form-disbursement-parts/select-bank.tsx',
            'src/components/otp-withdrawal-form/form-disbursement/form-disbursement.tsx',
            'src/components/otp-withdrawal-form/form-disbursement-V2/form-disbursement-v2.tsx',
            'src/components/otp-withdrawal-form/form-party/form-party.tsx',
            'src/components/otp-withdrawal-form/form-party/party-helpers.tsx',
            'src/components/otp-withdrawal-form/form-party/party-phone.tsx',
            'src/components/otp-withdrawal-form/form-program/contract-replacement.tsx',
            'src/components/otp-withdrawal-form/form-program/form-program-full-withdrawal.tsx',
            'src/components/otp-withdrawal-form/form-program/form-program-partial-withdrawal.tsx',
            'src/components/otp-withdrawal-form/form-program/form-program-process-date.tsx',
            'src/components/otp-withdrawal-form/irs-withholdings.tsx',
            'src/components/otp-withdrawal-form/loan-acknowledgement.tsx',
            'src/components/otp-withdrawal-form/maritial-status-allowance-withholdings.tsx',
            'src/components/otp-withdrawal-form/nea-benefits.tsx',
            'src/components/otp-withdrawal-form/phone-details.tsx',
            'src/components/otp-withdrawal-form/rmd-method/existing-programs.tsx',
            'src/components/otp-withdrawal-form/rmd-method/joint-life-expectancy.tsx',
            'src/components/otp-withdrawal-form/rmd-method/rmd-calculator.tsx',
            'src/components/otp-withdrawal-form/rmd-method/rmd-method.tsx',
            'src/components/otp-withdrawal-form/rmd-method/rmd-row.tsx',
            'src/components/otp-withdrawal-form/signature-validation/signature-validation-parts/core/is-valid-core.tsx',
            'src/components/otp-withdrawal-form/signature-validation/signature-validation-parts/core/signature-date-core.tsx',
            'src/components/otp-withdrawal-form/signature-validation/signature-validation-parts/signature-city-provided.tsx',
            'src/containers/side-sheet-tasks-filters/side-sheet-tasks-filters.tsx',
            'src/containers/subpages/activity-sub-page/activity-sub-page.tsx',
            'src/containers/subpages/funds-sub-page/cards/edit-allocations-side-sheet-content.tsx',
            'src/containers/subpages/funds-sub-page/cards/funds-card.tsx',
            'src/containers/task-container/components/side-panel/document-portal-panel.tsx',
            'src/containers/task-container/components/steps/claims/call-for-information.tsx',
            'src/containers/task-container/components/steps/task-form/task-form-step.tsx',
            'src/containers/task-container/components/steps/task-form/task-form.tsx',
            'src/containers/task-container/components/steps/task-review/task-review-step.tsx',
            'src/containers/task-container/components/steps/task-review/task-review.tsx',
            'src/containers/task-management-queue/task-management-queue-container.tsx',
            'src/contexts/ApplicationContext.tsx',
            'src/contexts/PolicySearchFilters.tsx',
            'src/hooks/otp-withdrawal/transaction-history.ts',
            'src/hooks/useDiaryNotes.ts',
            'src/hooks/useFetch.ts',
            'src/hooks/useFetchAssociatedAddress.tsx',
            'src/hooks/useOutsideClick.ts',
            'src/hooks/useServiceFormReview.ts',
            'src/hooks/useSpecialProgram.ts',
            'src/hooks/useTaskManagementQueue.tsx',
            'src/hooks/useWindowResize.ts',
            'src/pages/cases/index.tsx',
            'src/pages/contact-center/send-document/index.tsx',
            'src/pages/create-case/create/index.tsx',
            'src/pages/create-case/oft/[id]/index.tsx',
            'src/pages/create-case/renewal/[id]/index.tsx',
            'src/pages/create-case/rmd/[id]/index.tsx',
            'src/pages/create-case/ssw/[id]/index.tsx',
            'src/pages/create-case/withdrawal/[id]/index.tsx',
            'src/pages/illustrations/client-cases/quick-quote/index.tsx',
            'src/pages/ssw-edit/ssw-update/index.tsx',
            'src/components/otp-withdrawal-form/signature-validation/signature-validation-parts/signature-comment.tsx',
            'src/components/otp-withdrawal-form/signature-validation/signature-validation-parts/signature-present.tsx',
            'src/components/otp-withdrawal-form/signature-validation/signature-validation-parts/spousal-consent.tsx',
            'src/components/otp-withdrawal-form/signature-validation/signature-validation.tsx',
            'src/components/otp-withdrawal-form/signature-validation/signature-validations.tsx',
            'src/components/otp-withdrawal-form/ssw-program/glwb-wrapper.tsx',
            'src/components/otp-withdrawal-form/ssw-program/single-life-person-details.tsx',
            'src/components/otp-withdrawal-form/ssw-program/ssw-program.tsx',
            'src/components/otp-withdrawal-form/state-w4-form.tsx',
            'src/components/otp-withdrawal-form/tax-withholding-row.tsx',
            'src/components/otp-withdrawal-form/tax-withholding-specified.tsx',
            'src/components/otp-withdrawal-form/tax-withholdings.tsx',
            'src/components/policy-index/policy-index-card-view.tsx',
            'src/components/policy-layout.tsx',
            'src/components/side-sheet/case-details/related-tab.tsx',
            'src/components/side-sheet/diary-notes/diary-notes-content.tsx',
            'src/components/side-sheet/side-sheet-allocations/beneficiary-allocator.tsx',
            'src/components/side-sheet/side-sheet-allocations/side-sheet-allocations.tsx',
            'src/components/side-sheet/task-details-sidesheet/global-task-sidesheet-content.tsx',
            'src/components/ssw-edit/ssw-update/ssw-update.tsx',
            'src/components/transaction-cta/transaction-cta.tsx',
            'src/components/w4p-tax-form/w4p-tax-form.tsx',
            'src/components/workflows/start-step/start-step.tsx',
            'src/containers/active-filters/status-filter.tsx',
            'src/containers/address-change-container/components/confirm/confirm-step.tsx',
            'src/containers/address-change-container/components/contact-details/address-validator.tsx',
            'src/containers/address-change-container/components/contact-details/contact-details-step.tsx',
            'src/containers/address-change-container/components/contact-details/contact-details.helpers.tsx',
            'src/containers/address-change-container/components/signature/signature-step-helpers.tsx',
            'src/containers/bene-change/bene-change-container.tsx',
            'src/containers/bene-change/components/beneficiary-details/bene-identification/bene-identification.tsx',
            'src/containers/bene-change/components/steps/bene-details/bene-details-step.tsx',
            'src/containers/bene-change/components/steps/confirm/confirm-step.tsx',
            'src/containers/bene-change/components/steps/owner-info/owners-info-step.tsx',
            'src/containers/bene-change/components/steps/signature/signature-step-helpers.tsx',
            'src/containers/bene-change/components/steps/signature/signature-step.tsx',
            'src/containers/bene-change/components/steps/summary/summary-step.tsx',
            'src/containers/case-sub-page/index.tsx',
            'src/containers/death-claim-container/steps/death-claim-notifier/death-claim.tsx',
            'src/containers/death-claim-container/steps/death-claim-notifier/other-notifier.tsx',
            'src/containers/death-claim-container/steps/notification-method/notification-card.tsx',
            'src/containers/default-case/steps/default-case-form-step.tsx',
            'src/containers/financial-transactions/autopay/amount/amount.tsx',
            'src/containers/financial-transactions/autopay/confirm/confirm.tsx',
            'src/containers/financial-transactions/fund-transfer/transfer/transfer.tsx',
            'src/containers/financial-transactions/premium/new-premium/amount/amount.tsx',
            'src/containers/financial-transactions/premium/new-premium/confirm/confirm.tsx',
            'src/containers/financial-transactions/withdrawal/amount/amount.tsx',
            'src/containers/nigo-entry-container/components/side-panel/document-portal-panel.tsx',
            'src/containers/nigo-entry-container/components/steps/form-entry/form-entry-step.tsx',
            'src/containers/nigo-entry-container/components/steps/form-selection.tsx/form-selection-step.tsx',
            'src/containers/nigo-entry-container/components/steps/form-selection.tsx/transaction-document-selection.tsx',
            'src/containers/nigo-entry-container/components/steps/service-form-review/service-form-review.tsx',
            'src/containers/nigo-entry-container/components/tab-group-container.tsx',
            'src/containers/otp/oft-forms/dlic/dlic-oft-form.tsx',
            'src/containers/otp/oft-forms/flic/flic-oft-form.tsx',
            'src/containers/otp/oft-forms/gdmn/gdmn-oft-form.tsx',
            'src/containers/otp/oft-forms/gilico/glco-oft-form.tsx',
            'src/containers/otp/oft-forms/mass/mass-oft-form.tsx',
            'src/containers/otp/oft-forms/nasu/nasu-oft-form.tsx',
            'src/containers/otp/oft-forms/prdn/prdn-oft-form.tsx',
            'src/containers/otp/oft-forms/rsln/rsln-oft-form.tsx',
            'src/containers/otp/oft-forms/sbgc/sbgc-oft-form.tsx',
            'src/containers/otp/oft-forms/ulpc/ulpc-oft-form.tsx',
            'src/containers/otp/oft-forms/usaa/usaa-oft-form.tsx',
            'src/containers/otp/reg60-forms/components/disclosure-authorization/disclosure-authorization.tsx',
            'src/containers/otp/reg60-forms/mass-mutual/mass-mutual-reg60-form.tsx',
            'src/containers/otp/renewal-forms/dlic-form.tsx',
            'src/containers/otp/renewal-forms/mass-mutual-form.tsx',
            'src/containers/otp/renewal-forms/sbgc-form.tsx',
            'src/containers/otp/rmd-forms/dlic/dlic-rmd-form.tsx',
            'src/containers/otp/rmd-forms/flic-rmd-form.tsx',
            'src/containers/otp/rmd-forms/gdmn/gdmn-rmd-form.tsx',
            'src/containers/otp/rmd-forms/glco-rmd-form.tsx',
            'src/containers/otp/rmd-forms/mm-rmd-form.tsx',
            'src/containers/otp/rmd-forms/nasu/nasu-rmd-form.tsx',
            'src/containers/otp/rmd-forms/prdn/prdn-rmd-form.tsx',
            'src/containers/otp/rmd-forms/rsln/rsln-rmd-form.tsx',
            'src/containers/otp/rmd-forms/sbgc-rmd-form.tsx',
            'src/containers/otp/rmd-forms/ulpc/ulpc-rmd-form.tsx',
            'src/containers/otp/rmd-forms/usaa/usaa-rmd-form.tsx',
            'src/containers/otp/ssw-forms/dlic/dlic-ssw-form.tsx',
            'src/containers/otp/ssw-forms/flic/flic-ssw-form.tsx',
            'src/containers/otp/ssw-forms/gdmn/gdmn-ssw-form.tsx',
            'src/containers/otp/ssw-forms/glco/glco-ssw-form.tsx',
            'src/containers/otp/ssw-forms/mass/mass-ssw-form.tsx',
            'src/containers/otp/ssw-forms/prdn/prdn-ssw-form.tsx',
            'src/containers/otp/ssw-forms/rsln/rsln-ssw-form.tsx',
            'src/containers/otp/ssw-forms/sbgc/joint-covered-person-details.tsx',
            'src/containers/otp/ssw-forms/sbgc/sbgc-ssw-form.tsx',
            'src/containers/otp/ssw-forms/ulpc/ulpc-ssw-form.tsx',
            'src/containers/otp/ssw-forms/usaa/usaa-ssw-form.tsx',
            'src/containers/otp/withdrawal-forms/components/form-controls.tsx',
            'src/containers/otp/withdrawal-forms/components/form-provider.tsx',
            'src/containers/otp/withdrawal-forms/dlic/dlic-withdrawal-form.tsx',
            'src/containers/otp/withdrawal-forms/flic-withdrawal-form.tsx',
            'src/containers/otp/withdrawal-forms/gdmn/gdmn-withdrawal-form.tsx',
            'src/containers/otp/withdrawal-forms/gilico/gilico-withdrawal-form.tsx',
            'src/containers/otp/withdrawal-forms/mass/mass-withdrawal-form.tsx',
            'src/containers/otp/withdrawal-forms/nasu/nasu-withdrawal-form.tsx',
            'src/containers/otp/withdrawal-forms/rsln/rsln-withdrawal-form.tsx',
            'src/containers/otp/withdrawal-forms/sbgc-withdrawal-form.tsx',
            'src/containers/otp/withdrawal-forms/ulpc/ulpc-withdrawal-form.tsx',
            'src/containers/otp/withdrawal-forms/usaa/usaa-withdrawal-form.tsx',
            'src/containers/page-header/loans-page-header.tsx',
            'src/containers/people-data-cards/correspondence-card/correspondence-card.tsx',
            'src/containers/people-data-cards/phone-card/phone-card.tsx',
            'src/containers/role-change/role-change-container.tsx',
            'src/containers/role-change/steps/bene-details/bene-details-step.tsx',
            'src/containers/role-change/steps/confirm/confirm-step.tsx',
            'src/containers/role-change/steps/role-details/role-details-step.tsx',
        ],

        rules: {
            'react-hooks/exhaustive-deps': 'off',
        },
    },
];
