import { headers } from 'next/headers';
import { v4 as uuid4 } from 'uuid';

import {
  MfaChallengeInputs,
  MfaAssociateInputs,
  MfaSendChallengeInputs,
} from '@/types/auth';
import { Subdomains } from '@/types/carriers';
import { UserInfo } from '@/types/logging';
import { getAccessToken, getSession } from '@/utils/auth';
import { logError, logFatal, logTrace, logWarn } from '@/utils/logging/log-fns';
import {
  CommonLogContext,
  getUserInfoForLogging,
  LoggingModule,
  LoggingStage,
} from '@/utils/logging/server-logging';
import { FEATURE_FLAGS } from '@/utils/optimizely/flags';
import { AUTH0_SCOPE } from '@/utils/serverClientUtils';
import { getSubdomain } from '@/utils/url';

import { getFeatureFlags } from './feature-flags';
import { HttpRequest } from './http';

function getIp() {
  const FALLBACK_IP_ADDRESS = '0.0.0.0';
  const forwardedFor = headers().get('x-forwarded-for');

  if (forwardedFor) {
    return forwardedFor.split(',')[0] ?? FALLBACK_IP_ADDRESS;
  }

  return headers().get('x-real-ip') ?? FALLBACK_IP_ADDRESS;
}

// Check API Config file
enum Service {
  BPM = 'bpm',
  POLICY = '/policy/',
  AUTH0 = 'auth0',
  ENTERPRISE_SEARCH = 'enterprise-search',
  TRANSACTIONS = 'transactions',
  UNKNOWN = 'unknown',
}

const criticalServices: Service[] = [
  Service.BPM,
  Service.POLICY,
  Service.AUTH0,
  Service.ENTERPRISE_SEARCH,
];

interface ServerLoggingContext {
  user: UserInfo | undefined;
  url: string;
  method: string | undefined;
  file: string;
  function: string;
  correlationId: string;
}

function handleLogging(
  service: Service,
  status: number,
  loggingContext: ServerLoggingContext
) {
  if (service === Service.BPM && status === 400) {
    //do we want a log trace
    // When BPM returns a 400, it often doesnt mean theres an actual issue with the request, it just means something is ineligible,
    logTrace(
      `${LoggingModule.SERVER_HTTP_REQUEST}::BPM::400::request::${LoggingStage.COMPLETE}`,
      loggingContext
    );
    return;
  }

  if (status >= 500) {
    if (criticalServices.includes(service)) {
      logFatal(
        `${LoggingModule.SERVER_HTTP_REQUEST}::request::${LoggingStage.ERROR}`,
        loggingContext
      );
    } else {
      logError(
        `${LoggingModule.SERVER_HTTP_REQUEST}::request::${LoggingStage.ERROR}`,
        loggingContext
      );
    }
  } else if (status >= 400) {
    logWarn(
      `${LoggingModule.SERVER_HTTP_REQUEST}::request::${LoggingStage.ERROR}`,
      loggingContext
    );
  }
}

class ServerHttpRequest extends HttpRequest {
  public request = async (
    input: string | URL | Request,
    init?: RequestInit | undefined,
    loggingCtx?: CommonLogContext
  ): Promise<Response> => {
    const correlationId = loggingCtx?.correlationId || uuid4();
    const now = performance.now();
    const { accessToken } = await getAccessToken();
    const requestInit: RequestInit = init || {};

    const loggingContext: ServerLoggingContext = {
      user: await getUserInfoForLogging(),
      url: input?.toString(),
      method: init?.method,
      file: 'server-http.ts',
      function: 'request',
      correlationId,
    };

    // If we autogenerated a corro ID, lets log it and figure out where it was missing.
    if (!loggingCtx?.correlationId) {
      logTrace(
        `${LoggingModule.SERVER_HTTP_REQUEST}::request::${loggingContext.url}::Missing CorrelationID, auto generated one.`,
        loggingContext
      );
    }

    logTrace(
      `${LoggingModule.SERVER_HTTP_REQUEST}::request::${LoggingStage.START}`,
      loggingContext
    );

    if (!requestInit.headers) {
      requestInit.headers = {};
    }

    requestInit.headers = {
      // all backend services should be using this as the way to pass
      // correlationId through the system.
      'x-correlation-id': correlationId,
      ...requestInit.headers,
      Authorization: `Bearer ${accessToken}`,
    };

    const result = await fetch(input, requestInit);

    if (!result.ok) {
      const service = this.identifyService(input.toString());
      handleLogging(service, result.status, loggingContext);
    }

    logTrace('server-http::request::complete', {
      ...loggingContext,
      duration: performance.now() - now,
      requestStatus: result.status,
    });
    return result;
  };

  //TODO: add logging here
  public sendVerificationCode = async (email: string) => {
    let clientId = process.env.AUTH0_CLIENT_ID;
    let clientSecret = process.env.AUTH0_CLIENT_SECRET;

    const featureFlagDecisions = await getFeatureFlags();

    // client_id and client_secret here are using wellabe specific variables so that the email with the code
    // has the correct wellabe logo. This is a TEMPORARY change because it's the only way for us to know what
    // subdomain the user is on before sending the email since we do not have access to organizations through
    // this custom auth0 flow. These variables are defined on a separate auth0 application that is a duplicate of
    // the mypolicyview application
    if (featureFlagDecisions?.[FEATURE_FLAGS.WELLABE_AUTH_TOKENS]) {
      const subDomain = getSubdomain(headers());

      if (subDomain === Subdomains.WELLABE) {
        clientId = process.env.AUTH0_CLIENT_ID_WELB;
        clientSecret = process.env.AUTH0_CLIENT_SECRET_WELB;
      }
    }

    return fetch(`${process.env.AUTH0_ISSUER_BASE_URL}/passwordless/start`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      cache: 'no-store',
      body: JSON.stringify({
        client_id: clientId,
        client_secret: clientSecret,
        connection: 'email',
        email,
        send: 'code',
      }),
    });
  };

  //TODO: add logging here
  public verifyPasswordlessStartChallenge = async ({
    email,
    code,
  }: {
    email: string;
    code: string;
  }) => {
    return fetch(`${process.env.AUTH0_ISSUER_BASE_URL}/oauth/token`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'auth0-forwarded-for': getIp(),
      },
      cache: 'no-store',
      body: JSON.stringify({
        grant_type: 'http://auth0.com/oauth/grant-type/passwordless/otp',
        client_id: process.env.AUTH0_CLIENT_ID,
        client_secret: process.env.AUTH0_CLIENT_SECRET,
        audience: process.env.AUTH0_AUDIENCE,
        realm: 'email',
        scope: AUTH0_SCOPE,
        username: email,
        otp: code,
      }),
    });
  };

  //TODO: add logging here
  public getMfaAuthenticators = async (mfaToken: string) => {
    return fetch(`${process.env.AUTH0_ISSUER_BASE_URL}/mfa/authenticators`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${mfaToken}`,
      },
      cache: 'no-store',
    });
  };

  //TODO: add logging here
  public associateMfa = async (
    mfaToken: string,
    inputs: MfaAssociateInputs
  ) => {
    const { authenticatorType, phoneNumber } = inputs;
    const body = {
      authenticator_types: ['oob'],
      oob_channels: [authenticatorType],
      phone_number: phoneNumber,
    };
    return fetch(`${process.env.AUTH0_ISSUER_BASE_URL}/mfa/associate`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${mfaToken}`,
      },
      cache: 'no-store',
      body: JSON.stringify(body),
    });
  };

  //TODO: add logging here
  public sendMfaChallenge = async (inputs: MfaSendChallengeInputs) => {
    return fetch(`${process.env.AUTH0_ISSUER_BASE_URL}/mfa/challenge`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      cache: 'no-store',
      body: JSON.stringify({
        client_id: process.env.AUTH0_CLIENT_ID,
        client_secret: process.env.AUTH0_CLIENT_SECRET,
        mfa_token: inputs.mfaToken,
        challenge_type: inputs.challengeType,
        authenticator_id: inputs.authenticatorId,
      }),
    });
  };

  //TODO: add logging here
  public enrollMfa = async (inputs: MfaChallengeInputs) => {
    const formData = new URLSearchParams({
      grant_type: 'http://auth0.com/oauth/grant-type/mfa-oob',
      client_id: process.env.AUTH0_CLIENT_ID,
      client_secret: process.env.AUTH0_CLIENT_SECRET,
      mfa_token: inputs.mfaToken,
      oob_code: inputs.oobCode,
      binding_code: inputs.bindingCode,
    });
    return fetch(`${process.env.AUTH0_ISSUER_BASE_URL}/oauth/token`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      cache: 'no-store',
      body: formData.toString(),
    });
  };

  //TODO: add logging here
  public verifyMfaChallenge = async (inputs: MfaChallengeInputs) => {
    const formData = new URLSearchParams({
      grant_type: 'http://auth0.com/oauth/grant-type/mfa-oob',
      client_id: process.env.AUTH0_CLIENT_ID,
      client_secret: process.env.AUTH0_CLIENT_SECRET,
      mfa_token: inputs.mfaToken,
      oob_code: inputs.oobCode,
      binding_code: inputs.bindingCode,
    });
    const headers: HeadersInit = {
      'Content-Type': 'application/x-www-form-urlencoded',
    };

    if (inputs.isEnrollment) {
      headers.authorization = `Bearer ${inputs.mfaToken}`;
    }

    return fetch(`${process.env.AUTH0_ISSUER_BASE_URL}/oauth/token`, {
      method: 'POST',
      headers,
      cache: 'no-store',
      body: formData.toString(),
    });
  };

  //TODO: add logging here
  public refreshToken = async () => {
    const session = await getSession();

    return fetch(`${process.env.AUTH0_MANAGEMENT_API_AUDIENCE}/oauth/token`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      cache: 'no-store',
      body: JSON.stringify({
        grant_type: 'refresh_token',
        client_id: process.env.AUTH0_CLIENT_ID,
        client_secret: process.env.AUTH0_CLIENT_SECRET,
        refresh_token: session?.refreshToken,
      }),
    });
  };

  private identifyService(url: string): Service {
    if (url.includes(Service.BPM)) return Service.BPM;
    if (url.includes(Service.POLICY)) return Service.POLICY;
    if (url.includes(Service.AUTH0)) return Service.AUTH0;
    if (url.includes(Service.ENTERPRISE_SEARCH))
      return Service.ENTERPRISE_SEARCH;
    return Service.UNKNOWN;
  }
}

export const ServerApi = new ServerHttpRequest();
