/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * fund-information-api
 * OpenAPI spec version: 1.0.1
 */
import axios from 'axios'

import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
/**
 * type of fund
 */
export type VariableFundTypeEnum = typeof VariableFundTypeEnum[keyof typeof VariableFundTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VariableFundTypeEnum = {
  INVESTMENT: 'INVESTMENT',
  AGGREGATE: 'AGGREGATE',
} as const;

/**
 * properties only associated with variable funds
 */
export interface VariableFundCharacteristics {
  /**
   * identifiers for funds in aggregate
   * @minItems 1
   * @nullable
   */
  fundAccountIds?: string[] | null;
  variableFundType: VariableFundTypeEnum;
}

/**
 * specifies how renwals are to be processed
 */
export type RenewalCriteriaEnum = typeof RenewalCriteriaEnum[keyof typeof RenewalCriteriaEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RenewalCriteriaEnum = {
  NEW_MONEY: 'NEW_MONEY',
  CALENDAR_ANNIVERSARY: 'CALENDAR_ANNIVERSARY',
  CONTRACT_ANNIVERSARY: 'CONTRACT_ANNIVERSARY',
  DEPOSIT_DATE: 'DEPOSIT_DATE',
} as const;

/**
 * specifies how fund segments are created
 */
export interface SegmentPolicy {
  creationCriteria: CreationCriteriaEnum;
  /**
   * number of months between renewals, required for calendar or contract anniversary renewals
   * @minimum 0
   * @maximum 2147483647
   * @nullable
   */
  frequency?: number | null;
  /**
   * date upon which all investment must be removed from the fund
   * @nullable
   */
  hardCloseDate?: string | null;
  /**
   * identifier for fund to which all remaining money will be moved on the hard close date
   * @nullable
   */
  hardCloseReplacementFund?: string | null;
  renewalCriteria: RenewalCriteriaEnum;
  /**
   * date upon which no new investment in the fund can be made
   * @nullable
   */
  softCloseDate?: string | null;
}

/**
 * @nullable
 */
export type ProductRulesInvestmentModels = {[key: string]: {[key: string]: number}} | null;

/**
 * @nullable
 */
export type ProductRulesFunds = {[key: string]: FundUsageInfo} | null;

/**
 * @nullable
 */
export type ProductRulesDisbursementPriority = {[key: string]: DisbursementPrioirtyInfo} | null;

export interface ProductRules {
  /** @nullable */
  basisPoints?: string | null;
  disbursementCriteria?: DisbursementCriteriaEnum;
  disbursementMethod?: DisbursementMethodEnum;
  /** @nullable */
  disbursementPriority: ProductRulesDisbursementPriority;
  /** @nullable */
  funds: ProductRulesFunds;
  /** @nullable */
  investmentModels?: ProductRulesInvestmentModels;
  /** @nullable */
  planCode?: string | null;
}

/**
 * properties only associated with index funds
 */
export interface IndexedFundCharacteristics {
  /**
   * effective (current) cap rate
   * @nullable
   */
  capRate?: number | null;
  creditingStrategy: CreditingStrategyEnum;
  /**
   * identifier used for obtaining the daily price information for the related index
   * @nullable
   */
  dailiyPriceIdentifier: string | null;
  /**
   * guaranteed minimum cap rate
   * @nullable
   */
  guaranteedMinimumCapRate?: number | null;
  /**
   * guaranteed minimum interest rate for illustrations
   * @nullable
   */
  guaranteedMinimumInterestRate?: number | null;
  /**
   * guaranteed minimum participation rate
   * @nullable
   */
  guaranteedMinimumParticipationRate?: number | null;
  /**
   * the associated index used to determine actual interest paid for adminstration purposes
   * @nullable
   */
  index: string | null;
  /**
   * effective (current) interest rate for illustrations
   * @nullable
   */
  interestRate?: number | null;
  /**
   * maximum allowable interest rate for illustrations
   * @nullable
   */
  maximumIllustrativeInterestRate?: number | null;
  /**
   * effective (current) participation rate
   * @nullable
   */
  participationRate?: number | null;
}

/**
 * specifies how fund is used. note that any fund that is an interim account must specify the sweep day
 */
export interface FundUsageInfo {
  /** is the fund used as an interim account */
  isInterimAccount: boolean;
  /**
   * minimum allowed fund value
   * @nullable
   */
  minimumFundValue?: number | null;
  /**
   * @minimum 0
   * @maximum 29
   * @nullable
   */
  sweepDay?: number | null;
}

/**
 * how to disburse money from available fund segments
 */
export type FundLevelDisbursementMethodEnum = typeof FundLevelDisbursementMethodEnum[keyof typeof FundLevelDisbursementMethodEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FundLevelDisbursementMethodEnum = {
  FIFO: 'FIFO',
  LIFO: 'LIFO',
  PRO_RATA: 'PRO_RATA',
} as const;

/**
 * Type of Fund
 */
export type FundAccountTypeEnum = typeof FundAccountTypeEnum[keyof typeof FundAccountTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FundAccountTypeEnum = {
  FIXED: 'FIXED',
  HOLDING: 'HOLDING',
  LOAN: 'LOAN',
  MATCH: 'MATCH',
  INDEXED: 'INDEXED',
  VARIABLE: 'VARIABLE',
} as const;

/**
 * properties only associated with fixed funds
 */
export interface FixedFundCharacteristics {
  /**
   * TBD
   * @minimum 0
   * @maximum 2147483647
   */
  bonusPeriodFrequency: number;
  /** guaranteed minimum interest rate */
  guaranteedMinimumInterestRate: number;
  /** effective interest rate */
  interestRate: number;
}

export interface FundDescriptor {
  /**
   * Committee on Uniform Security Identification Procedures identifier
   * @nullable
   */
  cusip?: string | null;
  /**
   * Identifier needed to look up daily pricing information for fund (UVCloud Identifier)
   * @nullable
   */
  dailyPricingIdentifier?: string | null;
  fixedFund?: FixedFundCharacteristics;
  /**
   * Market Name
   * @nullable
   */
  fundAccountName: string | null;
  fundAccountType: FundAccountTypeEnum;
  fundSegmentPolicy?: SegmentPolicy;
  /**
   * User entered GL accounting code for fund accounting
   * @nullable
   */
  glCode?: string | null;
  indexedFund?: IndexedFundCharacteristics;
  /**
   * International Securities Identification Number (ISO 6166)
   * @nullable
   */
  isin?: string | null;
  /**
   * Minimum amount that can be moved in or out of this fund at any one instant in time
   * @nullable
   */
  minimumTransferAmount?: number | null;
  variableFund?: VariableFundCharacteristics;
}

/**
 * specifies which fund has money removed from first
 */
export interface DisbursementPrioirtyInfo {
  fundLevelDisbursementMethod?: FundLevelDisbursementMethodEnum;
  /**
   * specifies the order - lower numbers are hit first
   * @minimum 0
   * @maximum 2147483647
   */
  priority: number;
}

/**
 * specifies order in which value is removed from the fund
 */
export type DisbursementMethodEnum = typeof DisbursementMethodEnum[keyof typeof DisbursementMethodEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DisbursementMethodEnum = {
  PRO_RATA: 'PRO_RATA',
  FIFO: 'FIFO',
  LIFO: 'LIFO',
  FUND_SPECIFIC: 'FUND_SPECIFIC',
} as const;

/**
 * TBD
 */
export type DisbursementCriteriaEnum = typeof DisbursementCriteriaEnum[keyof typeof DisbursementCriteriaEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DisbursementCriteriaEnum = {
  DEPOSIT_DATE: 'DEPOSIT_DATE',
  ORIGINAL_DEPOSIT_DATE: 'ORIGINAL_DEPOSIT_DATE',
} as const;

/**
 * specifies how interest is to be credited
 */
export type CreditingStrategyEnum = typeof CreditingStrategyEnum[keyof typeof CreditingStrategyEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreditingStrategyEnum = {
  POINT_2_POINT: 'POINT_2_POINT',
  MONTHLY_AVERAGE: 'MONTHLY_AVERAGE',
  MONTHLY_SUM: 'MONTHLY_SUM',
  ANNUAL_AVERAGE: 'ANNUAL_AVERAGE',
  SEMIANNUAL_AVERAGE: 'SEMIANNUAL_AVERAGE',
  POINT_2_POINT_13_MONTH_AVERAGE: 'POINT_2_POINT_13_MONTH_AVERAGE',
} as const;

/**
 * specifies when new segments are created
 */
export type CreationCriteriaEnum = typeof CreationCriteriaEnum[keyof typeof CreationCriteriaEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreationCriteriaEnum = {
  DEPOSIT_DATE: 'DEPOSIT_DATE',
  ORIGINAL_DEPOSIT_DATE: 'ORIGINAL_DEPOSIT_DATE',
} as const;





  /**
 * @summary Get all known fund identifiers
 */
export const getFundsV1CarriersCarrierIdFunds = <TData = AxiosResponse<string[]>>(
    carrierId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/funds/v1/carriers/${carrierId}/funds`,options
    );
  }

/**
 * @summary Get fund information for the specified fund
 */
export const getFundsV1CarriersCarrierIdFundsFundId = <TData = AxiosResponse<FundDescriptor>>(
    carrierId: string,
    fundId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/funds/v1/carriers/${carrierId}/funds/${fundId}`,options
    );
  }

/**
 * @summary List all products for which fund configuration rules are stored
 */
export const getFundsV1CarriersCarrierIdProducts = <TData = AxiosResponse<string[]>>(
    carrierId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/funds/v1/carriers/${carrierId}/products`,options
    );
  }

/**
 * @summary Retrieve the fund rules for the specified product
 */
export const getFundsV1CarriersCarrierIdProductsProductId = <TData = AxiosResponse<ProductRules>>(
    carrierId: string,
    productId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/funds/v1/carriers/${carrierId}/products/${productId}`,options
    );
  }

export type GetFundsV1CarriersCarrierIdFundsResult = AxiosResponse<string[]>
export type GetFundsV1CarriersCarrierIdFundsFundIdResult = AxiosResponse<FundDescriptor>
export type GetFundsV1CarriersCarrierIdProductsResult = AxiosResponse<string[]>
export type GetFundsV1CarriersCarrierIdProductsProductIdResult = AxiosResponse<ProductRules>
