declare global {
  namespace NodeJS {
    interface ProcessEnv {
      AUTH0_COOKIE_DOMAIN: string;
      AUTH0_COOKIE_DOMAIN_MYPOLICYVIEW: string;
      AUTH0_ISSUER_BASE_URL: string;
      AUTH0_AUDIENCE: string;
      NEXT_PUBLIC_AUTH0_COOKIE_DOMAIN: string;
      NEXT_PUBLIC_AUTH0_COOKIE_DOMAIN_MYPOLICYVIEW: string;
      NEXT_PUBLIC_BACKEND_URL: string;
      NEXT_PUBLIC_MOCK_API_REQUEST: string;
      NEXT_PUBLIC_BASE_URL: string;
      NEXT_PUBLIC_DATADOG_ENV: string;
      NEXT_PUBLIC_DATADOG_APPLICATION_ID: string;
      NEXT_PUBLIC_DATADOG_CLIENT_TOKEN: string;
      NEXT_PUBLIC_DATADOG_BROWSER_APPLICATION_ID: string;
      NEXT_PUBLIC_SEGMENT_ANALYTICS_KEY: string;
      NEXT_PUBLIC_FARMERS_API_BASE_URL: string;
      AUTH0_SCOPE: string;
      SESSION_DURATION_IN_MINUTES: string;
      CHECK_SESSION_THRESHOLD_IN_MINUTES: string;
      AUTH0_SESSION_NAME: string;
      JWT_SECRET: string;
      AUTH0_CLIENT_ID: string;
      AUTH0_CLIENT_SECRET: string;
      AUTH0_CLIENT_ID_WELB: string;
      AUTH0_CLIENT_SECRET_WELB: string;
      NEXT_PUBLIC_AUTH0_BASE_URL: string;
      AUTH0_COOKIE_SECURE: string;
      AUTH0_MANAGEMENT_API_AUDIENCE: string;
      NEXT_PUBLIC_CALL_LOG_X_API_KEY: string;
      NEXT_PUBLIC_SSO_FARMERS_REDIRECT_BASE_URL: string;
    }
  }
}

export {};
