name: 'Build and Deploy Portal Frontend - East'

on:
  push:

jobs:
  uat-deploy-east:
    if: startsWith(github.ref_name, 'release/ops/')
    uses: ./.github/workflows/deploy-ops-east.yml
    with:
      environment-level: uat
    secrets: inherit
