name: 'Build and Deploy'

on:
  push:
    paths:
      - 'apps/consumer-experience/**'

jobs:
  dev-deploy:
    if: github.ref_name == 'dev'
    uses: ./.github/workflows/deploy-consumer-experience-action.yml
    with:
      environment-level: qa
    secrets: inherit

  uat-deploy:
    if: startsWith(github.ref_name, 'release/')
    uses: ./.github/workflows/deploy-consumer-experience-action.yml
    with:
      environment-level: uat
    secrets: inherit
