name: 'Build and Deploy Portal Frontend - East'

on:
  push:
    paths:
      - 'apps/ops/**'

jobs:
  dev-deploy-east:
    if: github.ref_name == 'feat/depu-4063--remove-corepack-integrity'
    uses: ./.github/workflows/deploy-ops-east.yml
    with:
      environment-level: qa
    secrets: inherit
