name: 'Build and Deploy Portal Frontend - East'

on:
  push:

jobs:
  uat-deploy-east:
    if: startsWith(github.ref_name, 'release/portal-frontend/')
    uses: ./.github/workflows/deploy-portal-frontend-east.yml
    with:
      environment-level: dev
    secrets: inherit
