name: 'Build and Deploy SSO MPV'

on:
  workflow_dispatch:
    inputs:
      environment-level:
        description: 'Select the environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - qa
          - uat
          - Production

jobs:
  deploy-east:
    uses: ./.github/workflows/build-sso-mpv.yml
    with:
      environment-level: ${{ inputs.environment-level }}
    secrets: inherit
