name: 'Build and Deploy Consumer Experience UAT'

on:
  push:

jobs:
  uat-deploy:
    if: startsWith(github.ref_name, 'release/consumer-experience/')
    uses: ./.github/workflows/deploy-consumer-experience-action.yml
    with:
      environment-level: uat
    secrets: inherit
