name: 'Build and Deploy Consumer Experience'

on:
  push:
    paths:
      - 'apps/consumer-experience/**'

jobs:
  dev-deploy:
    if: github.ref_name == 'dev'
    uses: ./.github/workflows/deploy-consumer-experience-action.yml
    with:
      environment-level: qa
    secrets: inherit
