name: "Chromatic CI"

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths:
      - "packages/bloom/**"

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: |
            - args: [--filter @zinnia/bloom]
      - name: Publish to Bloom to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
          skip: "dependabot/**"
          workingDir: packages/bloom
