name: 'Production Consumer Experience Deployment'

on:
  workflow_dispatch:

jobs:
  prod-deploy:
    if: startsWith(github.ref_name, 'release/consumer-experience/')
    uses: ./.github/workflows/deploy-consumer-experience-action.yml
    with:
      environment-level: production
    secrets: inherit
