name: 'Chromatic Consumer Experience'

on:
  workflow_dispatch:
  push:
    paths:
      - 'apps/consumer-experience/**'
    branches-ignore:
      - 'dependabot/**'

jobs:
  chromatic:
    uses: './.github/workflows/build-consumer-experience-chromatic.yml'
    with:
      project-name: Consumer Experience
      filter-path: consumer-experience
      working-dir: apps/consumer-experience
    secrets:
      chromatic-token: ${{ secrets.CHROMATIC_PROJECT_TOKEN_CXP }}
