name: 'Consumer Experience Dev to UAT'

on:
  workflow_dispatch:

jobs:
  dev-deploy:
    if: github.ref_name == 'dev'
    uses: ./.github/workflows/deploy-consumer-experience-action.yml
    with:
      environment-level: uat
    secrets: inherit
