name: Portal Frontend Deploy branch to UAT
on:
  workflow_dispatch:

jobs:
  dev-deploy-east:
    uses: ./.github/workflows/deploy-ops-east.yml
    with:
      environment-level: uat
    secrets: inherit
