name: 'Chromatic OPS'

on:
  workflow_call:
  # push:
  # paths:
  # - 'apps/ops/**'
  # branches-ignore:
  # - 'dependabot/**'

jobs:
  chromatic:
    uses: './.github/workflows/build-chromatic.yml'
    with:
      project-name: OPS
      filter-path: ops
      working-dir: apps/ops
    secrets:
      chromatic-token: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
