name: 'Chromatic POM'

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/pom/**'
    branches-ignore:
      - 'dependabot/**'

jobs:
  chromatic:
    uses: './.github/workflows/build-chromatic.yml'
    with:
      project-name: POM
      filter-path: '@zinnia/pom'
      working-dir: packages/pom
    secrets:
      chromatic-token: ${{ secrets.CHROMATIC_PROJECT_TOKEN_POM }}
