name: 'Chromatic xd-components'

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/xd-components/**'
    branches-ignore:
      - 'dependabot/**'

jobs:
  chromatic:
    uses: './.github/workflows/build-chromatic.yml'
    with:
      project-name: XD-Components
      filter-path: '@zinnia/xd-components'
      working-dir: packages/xd-components
    secrets:
      chromatic-token: ${{ secrets.CHROMATIC_PROJECT_TOKEN_XD_COMPONENTS }}
