name: 'Zinnia Live Release Branch to UAT'

on:
  workflow_dispatch:

jobs:
  dev-deploy-east:
    if: startsWith(github.ref_name, 'release/zinnia-live-v')
    uses: ./.github/workflows/deploy-ops-east.yml
    with:
      environment-level: uat
    secrets: inherit
