openapi: 3.0.3
info:
  title: Zinnia Transaction Store
  description: Zinnia Transaction Store.
  version: 1.0.2
servers:
  - url: https://qa.api.zinnia.io
    description: QA Environment
  - url: https://dev.api.zinnia.io
    description: DEV Environment
  - url: https://uat-bpm.se2.com
    description: UAT Environment
  - url: https://bpm.se2.com
    description: PROD Environment
tags:
  - name: TransactionData
    description: TransactionData
  - name: TransactionData Search
    description: TransactionData Search
paths:
  /transactions/v1/transaction:
    post:
      tags:
        - TransactionData
      summary: Save TransactionData
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionModelRequest'
        required: true
      responses:
        '200':
          description: Transaction Model success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionModelResponse'
        '500':
          description: Internal server error. Please check server logs for more details.
  /transactions/v1/transaction/entities/{transactionId}:
    get:
      tags:
        - TransactionData
      summary: Get TransactionData by transactionId
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Transaction Model success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionModelResponse'
        '500':
          description: Internal server error. Please check server logs for more details.
    put:
      tags:
        - TransactionData
      summary: Update TransactionData by transactionId
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionModelRequest'
        required: true
      responses:
        '200':
          description: Transaction Model success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionModelResponse'
        '500':
          description: Internal server error. Please check server logs for more details.
  /transactions/v1/transaction/search:
    post:
      tags:
        - TransactionData
      summary: Search TransactionData
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionSearchRequestModel'
        required: true
      responses:
        '200':
          description: Transaction Model success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionModelList'
        '500':
          description: Internal server error. Please check server logs for more details.
  /transactions/v1/transaction/{correlationId}/entities:
    get:
      tags:
        - TransactionData
      summary: Get TransactionData by correlationId and associated query param filter
      parameters:
        - name: correlationId
          in: path
          required: true
          schema:
            type: string
        - name: entityType
          in: query
          description: entityType.
          required: false
          schema:
            type: string
        - name: createdTs
          in: query
          description: createdTs.
          required: false
          schema:
            type: string
            format: date
            example: '2024-01-01T00:00:00.000Z'
        - name: updatedTs
          in: query
          description: updatedTs.
          required: false
          schema:
            type: string
            format: date
            example: '2024-01-01T00:00:00.000Z'
      responses:
        '200':
          description: Transaction Model success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionModelList'
        '500':
          description: Internal server error. Please check server logs for more details.
  /transactions/v1/transaction/{correlationId}/entities/{entityType}/{entityId}:
    get:
      tags:
        - TransactionData
      summary: Save TransactionData
      parameters:
        - name: correlationId
          in: path
          required: true
          schema:
            type: string
        - name: entityType
          in: path
          required: true
          schema:
            type: string
        - name: entityId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Transaction Model success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionModelList'
        '500':
          description: Internal server error. Please check server logs for more details.
  /transactions/v1/entities/{entityType}/search:
    post:
      tags:
        - TransactionData Search
      summary: Search TransactionData
      parameters:
        - name: entityType
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionDataEntitySearchRequest'
        required: true
      responses:
        '200':
          description: Transaction Model success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionModelList'
        '500':
          description: Internal server error. Please check server logs for more details.
  /transactions/v1/transaction/entities/{entityType}/search:
    get:
      tags:
        - TransactionData
      summary: Save TransactionData
      parameters:
        - name: entityType
          in: path
          required: true
          schema:
            type: string
        - name: identifierParams
          in: query
          required: false
          description: Key-value pairs used to filter transactions.
          schema:
            type: object
            additionalProperties:
              type: string
      responses:
        '200':
          description: Transaction Model success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionModelList'
        '500':
          description: Internal server error. Please check server logs for more details.
components:
  schemas:
    TransactionModelRequest:
      type: object
      description: Model for a transaction date request.
      properties:
        correlationId:
          type: string
          description: Unique identifier for correlation.
        transactionType:
          type: string
          description: Type of transaction.
        carrier:
          type: string
          description: Carrier associated with the transaction.
        source:
          type: string
          description: Source of the transaction.
        entityType:
          type: string
          description: Type of the entity involved.
        entityId:
          type: string
          description: Unique identifier for the entity.
        entity:
          type: object
          description: Actual entity information as JSON Object.
        expireTs:
          type: string
          format: date-time
          description: Expiration timestamp.
        createdBy:
          type: string
          description: Creator of the transaction.
        updatedBy:
          type: string
          description: Last updater of the transaction.
        identifiers:
          type: array
          description: List of identifiers associated with the transaction.
          items:
            $ref: '#/components/schemas/Identifiers'
    TransactionModelList:
      type: array
      description: A list of TransactionModel Response.
      items:
        $ref: '#/components/schemas/TransactionModelResponse'
    TransactionModelResponse:
      type: object
      description: Model for a transaction with detailed information.
      properties:
        recordId:
          type: string
          description: Unique identifier for the transaction record.
        correlationId:
          type: string
          description: Correlation ID associated with the transaction.
        transactionType:
          type: string
          description: Type of transaction.
        carrier:
          type: string
          description: Carrier associated with the transaction.
        source:
          type: string
          description: Source of the transaction.
        entityType:
          type: string
          description: Type of the entity involved.
        entityId:
          type: string
          description: Unique identifier for the entity.
        entity:
          type: object
          description: Actual entity information as JSON Object.
        expireTs:
          type: string
          format: date-time
          description: Expiration timestamp for the transaction.
        createdTs:
          type: string
          format: date-time
          description: Timestamp when the transaction was created.
        updatedTs:
          type: string
          format: date-time
          description: Timestamp when the transaction was last updated.
        createdBy:
          type: string
          description: User or system that created the transaction.
        updatedBy:
          type: string
          description: User or system that last updated the transaction.
        identifiers:
          type: array
          description: List of identifiers related to the transaction.
          items:
            $ref: '#/components/schemas/Identifiers'
    Identifiers:
      type: object
      description: Identifier model with key-value pair.
      properties:
        identifier:
          type: string
          description: Identifier key.
        value:
          type: string
          description: Identifier value.
    TransactionSearchRequestModel:
      type: object
      description: Model for searching transactions based on various criteria.
      properties:
        correlationId:
          type: array
          description: List of correlation IDs to search for.
          items:
            type: string
        identifiers:
          type: array
          description: List of identifiers related to the transaction.
          items:
            $ref: '#/components/schemas/Identifiers'
        transactionType:
          type: array
          description: List of transaction types to search for.
          items:
            type: string
        entityType:
          type: array
          description: List of entity types to search for.
          items:
            type: string
    TransactionDataEntitySearchRequest:
      type: object
      description: Model for a transaction search with entity search.
      properties:
        identifiers:
          type: array
          description: List of identifiers related to the transaction.
          items:
            $ref: '#/components/schemas/Identifiers'
        entity:
          type: object
          description: >-
            A map of entity details, where the keys are strings and the values
            can be any type.
          additionalProperties:
            type: object
  securitySchemes:
    Auth0:
      type: openIdConnect
      openIdConnectUrl: https://login.qa.zinnia.com/.well-known/openid-configuration
      x-kong-security-openid-connect:
        config:
          run_on_preflight: true
          scopes_claim:
            - https://qa.api.zinnia.io/permissions
          audience_claim:
            - aud
          audience_required:
            - https://qa.api.zinnia.io
          client_id:
            - client_id
          auth_methods:
            - bearer
        enabled: true
        protocols:
          - grpc
          - grpcs
          - http
          - https
